/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Admin;


import Control.Doctor_RegisterController2;
import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;
/**
 *
 * @author Deshan Asanka
 */
public class Add_Doctor extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Add_Doctor() {
        initComponents();
        setBackground(new Color(1.0f,1.0f,1.0f,0.8f));   
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 35, 35));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        clear = new javax.swing.JLabel();
        d_id = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        add = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        panelRound2 = new Design.PanelRound();
        panelRound1 = new Design.PanelRound();
        username = new javax.swing.JTextField();
        password2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        id = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        contactno = new javax.swing.JTextField();
        NIC = new javax.swing.JTextField();
        roomno = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        specialization = new javax.swing.JComboBox<>();
        username1 = new javax.swing.JLabel();
        contactno1 = new javax.swing.JLabel();
        roomno1 = new javax.swing.JLabel();
        years = new javax.swing.JLabel();
        specialization1 = new javax.swing.JLabel();
        nic = new javax.swing.JLabel();
        d_name = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        clear.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        clear.setForeground(new java.awt.Color(102, 102, 102));
        clear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clear.setText("Clear");
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(410, 590, 90, 40);

        d_id.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        d_id.setText("Doctor ID :");
        d_id.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(d_id);
        d_id.setBounds(200, 130, 130, 30);

        gender.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        gender.setText("Gender :");
        gender.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(gender);
        gender.setBounds(200, 230, 100, 30);

        add.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add.setText("ADD");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(740, 590, 120, 40);

        cancel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancel.setText("CANCEL");
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(550, 590, 120, 40);

        panelRound2.setBackground(new java.awt.Color(193, 193, 193));
        panelRound2.setRoundBottomLeft(15);
        panelRound2.setRoundBottomRight(15);
        panelRound2.setRoundTopLeft(15);
        panelRound2.setRoundTopRight(15);
        getContentPane().add(panelRound2);
        panelRound2.setBounds(550, 590, 120, 40);

        panelRound1.setBackground(new java.awt.Color(15, 225, 111));
        panelRound1.setRoundBottomLeft(15);
        panelRound1.setRoundBottomRight(15);
        panelRound1.setRoundTopLeft(15);
        panelRound1.setRoundTopRight(15);
        getContentPane().add(panelRound1);
        panelRound1.setBounds(740, 590, 120, 40);

        username.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        username.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(380, 490, 260, 30);

        password2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        password2.setText("Password :");
        password2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(password2);
        password2.setBounds(200, 540, 110, 30);

        password.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(password);
        password.setBounds(380, 540, 260, 36);

        id.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        id.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id);
        id.setBounds(380, 130, 380, 30);

        year.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        year.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                yearKeyPressed(evt);
            }
        });
        getContentPane().add(year);
        year.setBounds(900, 340, 120, 30);

        name.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        name.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(380, 180, 640, 30);

        contactno.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        contactno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnoActionPerformed(evt);
            }
        });
        contactno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contactnoKeyPressed(evt);
            }
        });
        getContentPane().add(contactno);
        contactno.setBounds(380, 390, 260, 30);

        NIC.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        NIC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(NIC);
        NIC.setBounds(380, 290, 260, 30);

        roomno.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        roomno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(roomno);
        roomno.setBounds(380, 440, 260, 30);

        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        male.setText("Male");
        male.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        getContentPane().add(male);
        male.setBounds(380, 230, 110, 30);

        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        female.setText("Female");
        female.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(female);
        female.setBounds(590, 230, 160, 30);

        specialization.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        specialization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anesthesia", "Animal Welfare", "Behavior", "Dentistry", "Dermatology", "Oncology", "Microbiology", "Nutrition", "Ophthalmology", "Pathology", "Radiology", "Surgery", "Theriogenology" }));
        specialization.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(specialization);
        specialization.setBounds(380, 340, 260, 30);

        username1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        username1.setText("Username :");
        username1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(username1);
        username1.setBounds(200, 490, 120, 30);

        contactno1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        contactno1.setText("Contact No:");
        contactno1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(contactno1);
        contactno1.setBounds(200, 390, 130, 30);

        roomno1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        roomno1.setText("Room No :");
        roomno1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(roomno1);
        roomno1.setBounds(200, 440, 110, 30);

        years.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        years.setText("Years of Experience :");
        years.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(years);
        years.setBounds(680, 340, 210, 30);

        specialization1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        specialization1.setText("Specialization :");
        specialization1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(specialization1);
        specialization1.setBounds(200, 340, 170, 30);

        nic.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        nic.setText("NIC N0 :");
        nic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(nic);
        nic.setBounds(200, 290, 100, 30);

        d_name.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        d_name.setText("Doctor Name :");
        d_name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(d_name);
        d_name.setBounds(200, 180, 150, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/ADD POP1.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 1200, 675);

        setSize(new java.awt.Dimension(1200, 679));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
    }//GEN-LAST:event_maleActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed

    }//GEN-LAST:event_nameActionPerformed

    private void contactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnoActionPerformed
 
    }//GEN-LAST:event_contactnoActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        this.setVisible(false); //disappear the interface
    }//GEN-LAST:event_cancelMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
String gender = null;
if (male.isSelected()) {
gender = "Male" ; 
} else if (female.isSelected()){
gender = "Female";
}

String special = specialization.getSelectedItem().toString();
//error message when not adding all the credentials 
if (id.getText().trim().isEmpty() || username.getText().trim().isEmpty()||password.getText().trim().isEmpty() ){
                 JOptionPane.showMessageDialog(null,"Add all the credentials", "Error" , JOptionPane.ERROR_MESSAGE);}
             else{
     //add records to the database
                 Doctor_RegisterController2.Form(id.getText(), name.getText(),gender, NIC.getText(),special,year.getText(), contactno.getText(), roomno.getText(),username.getText(),password.getText());
this.setVisible(false);
             }
    }//GEN-LAST:event_addMouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
    
    }//GEN-LAST:event_usernameActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
  
    }//GEN-LAST:event_idActionPerformed

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        // clear field
    id.setText("");
    name.setText("");
    NIC.setText("");
    year.setText("");
    contactno.setText("");
    roomno.setText("");
    username.setText("");
    password.setText("");
    male.setSelected(true);
    specialization.setSelectedIndex(0);
    }//GEN-LAST:event_clearMouseClicked

    private void yearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearKeyPressed
       //error message when adding characters   
        char c = evt.getKeyChar();
if(Character.isLetter(c)){
  year.setEditable(false);
   JOptionPane.showMessageDialog(null, "Please Enter Numbers only", "Error",JOptionPane.ERROR_MESSAGE);

}
else
{
  year.setEditable(true);   
}       
    }//GEN-LAST:event_yearKeyPressed

    private void contactnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactnoKeyPressed
 //error message when adding characters            
        char c = evt.getKeyChar();
if(Character.isLetter(c)){
  contactno.setEditable(false);
   JOptionPane.showMessageDialog(null, "Please Enter Numbers only", "Error",JOptionPane.ERROR_MESSAGE);

}
else
{
  contactno.setEditable(true);   
}  
    }//GEN-LAST:event_contactnoKeyPressed

    /**
     * @param args the command line arguments
     */
 //clear field   
public void clearField(){
id.setText("");
name.setText("");
NIC.setText("");
year.setText("");
contactno.setText("");
roomno.setText("");
username.setText("");
password.setText("");
male.setSelected(true);}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NIC;
    private javax.swing.JLabel add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel clear;
    private javax.swing.JTextField contactno;
    private javax.swing.JLabel contactno1;
    private javax.swing.JLabel d_id;
    private javax.swing.JLabel d_name;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel gender;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nic;
    private Design.PanelRound panelRound1;
    private Design.PanelRound panelRound2;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel password2;
    private javax.swing.JTextField roomno;
    private javax.swing.JLabel roomno1;
    private javax.swing.JComboBox<String> specialization;
    private javax.swing.JLabel specialization1;
    private javax.swing.JTextField username;
    private javax.swing.JLabel username1;
    private javax.swing.JTextField year;
    private javax.swing.JLabel years;
    // End of variables declaration//GEN-END:variables
}
