/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Admin;


import Model.Channel_Search;
import Model.DBConnection;
import Model.Doctor_Searchtable;
import Model.Pet_Searchtable;
import Model.Pharmacist_Searchtable;
import Model.Receptionist_Searchtable;
import View.Login_user_type;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Deshan Asanka
 */
public class Admin_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Dashboard
     */
    
    
      String uname;  
     
    public Admin_Dashboard(String user_name) {
        initComponents();
       
        this.uname = user_name;
        username.setText(uname); //set username
        
        //doctor count
        ResultSet r = new Doctor_Searchtable().searchDoctor();
        DefaultTableModel dtm = (DefaultTableModel) doc.getModel();
        dtm.setRowCount(0); //sets the number of rows in the model
        try{
            Vector v;
            while (r.next()){
                v = new Vector();
                v.add(r.getString("d_id"));
                      dtm.addRow(v); }
            DBConnection.closeCon();
        }catch (Exception e) {
            e.printStackTrace();}
        
        int count = doc.getRowCount(); 
        d_count.setText(String.valueOf(count));
        
        //pet count
        ResultSet n = new Pet_Searchtable().searchpet();
        DefaultTableModel ntm = (DefaultTableModel) pet_table.getModel();
        ntm.setRowCount(0); //sets the number of rows in the model
        try{
            Vector v;
            while (n.next()){
                v = new Vector();
                v.add(n.getString("id"));
               

                ntm.addRow(v); }
            DBConnection.closeCon();  }
        catch (Exception e) {
            e.printStackTrace(); }
         int pcount = pet_table.getRowCount(); 
        p_count.setText(String.valueOf(pcount));

//receptionist count        
ResultSet h = new Receptionist_Searchtable().searchreceptionist();
DefaultTableModel htm = (DefaultTableModel) rec.getModel();
htm.setRowCount(0); //sets the number of rows in the model
try{
Vector v;
while (h.next()){
v = new Vector();
v.add(h.getString("r_id"));

htm.addRow(v);}
DBConnection.closeCon();}
catch (Exception e) {
e.printStackTrace();}

  int rcount = rec.getRowCount(); 
        r_count.setText(String.valueOf(rcount));
        
//pharmacist count       
ResultSet k = new Pharmacist_Searchtable().searchPharmacist();
DefaultTableModel ktm = (DefaultTableModel) pha.getModel();
ktm.setRowCount(0); //sets the number of rows in the model
try{
Vector v;
while (k.next()){
v = new Vector();
v.add(k.getString("id"));

ktm.addRow(v);}
DBConnection.closeCon();}
catch (Exception e) {
e.printStackTrace();}

  int phcount = pha.getRowCount(); 
  ph_count.setText(String.valueOf(phcount));
  
//channel count
ResultSet a = new Channel_Search().searchChannel();
DefaultTableModel atm = (DefaultTableModel) cha.getModel();
atm.setRowCount(0); //sets the number of rows in the model
try{
Vector v;
while (a.next()){
v = new Vector();
v.add(a.getString("channel_no"));

atm.addRow(v);
}
DBConnection.closeCon();
}
catch (Exception e) {
e.printStackTrace();
}
int cha_count = cha.getRowCount(); 
  channe_count.setText(String.valueOf(cha_count));
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        TopBar_Back = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        pha = new javax.swing.JTable();
        TopBar = new javax.swing.JPanel();
        Maxi = new javax.swing.JLabel();
        Mini = new javax.swing.JLabel();
        Cross = new javax.swing.JLabel();
        DASHI = new javax.swing.JLabel();
        Dashboard = new javax.swing.JLabel();
        panelRound2 = new Design.PanelRound();
        panelRound1 = new Design.PanelRound();
        panelRound3 = new Design.PanelRound();
        Profile_Image = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        usertype = new javax.swing.JLabel();
        SideMenuBar_Back = new javax.swing.JPanel();
        SideMenuBar = new javax.swing.JPanel();
        pharm = new javax.swing.JLabel();
        doctor = new javax.swing.JLabel();
        pet = new javax.swing.JLabel();
        recept = new javax.swing.JLabel();
        LogOut = new javax.swing.JLabel();
        PAI = new javax.swing.JLabel();
        PHI = new javax.swing.JLabel();
        REI = new javax.swing.JLabel();
        LOI = new javax.swing.JLabel();
        DOI = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doc = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        pet_table = new javax.swing.JTable();
        panelRound6 = new Design.PanelRound();
        panelRound22 = new Design.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        d_count = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelRound13 = new Design.PanelRound();
        panelRound24 = new Design.PanelRound();
        jLabel6 = new javax.swing.JLabel();
        ph_count = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        panelRound15 = new Design.PanelRound();
        panelRound26 = new Design.PanelRound();
        jLabel26 = new javax.swing.JLabel();
        channe_count = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        panelRound12 = new Design.PanelRound();
        panelRound23 = new Design.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        p_count = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        panelRound14 = new Design.PanelRound();
        panelRound25 = new Design.PanelRound();
        jLabel13 = new javax.swing.JLabel();
        r_count = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        rec = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        cha = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 675));
        setMinimumSize(new java.awt.Dimension(1200, 675));
        setUndecorated(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(239, 252, 245));
        Background.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 232, 221), 4, true));
        Background.setMaximumSize(new java.awt.Dimension(1200, 675));
        Background.setMinimumSize(new java.awt.Dimension(1200, 675));
        Background.setPreferredSize(new java.awt.Dimension(1200, 675));

        TopBar_Back.setBackground(new java.awt.Color(232, 244, 233));
        TopBar_Back.setPreferredSize(new java.awt.Dimension(656, 50));

        pha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        pha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(pha);

        TopBar.setBackground(new java.awt.Color(255, 255, 255));
        TopBar.setPreferredSize(new java.awt.Dimension(656, 50));

        Maxi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Maxi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/max.png"))); // NOI18N
        Maxi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Maxi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaxiMouseClicked(evt);
            }
        });

        Mini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/minimize.png"))); // NOI18N
        Mini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniMouseClicked(evt);
            }
        });

        Cross.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cross.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/Cross.png"))); // NOI18N
        Cross.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cross.setPreferredSize(new java.awt.Dimension(25, 25));
        Cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrossMouseClicked(evt);
            }
        });

        DASHI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_fries_menu_30px_1.png"))); // NOI18N

        Dashboard.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(96, 125, 139));
        Dashboard.setText("Dashboard");

        javax.swing.GroupLayout TopBarLayout = new javax.swing.GroupLayout(TopBar);
        TopBar.setLayout(TopBarLayout);
        TopBarLayout.setHorizontalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DASHI)
                .addGap(18, 18, 18)
                .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Mini, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Maxi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Cross, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TopBarLayout.setVerticalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Dashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(DASHI, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Mini, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Maxi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Cross, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TopBar_BackLayout = new javax.swing.GroupLayout(TopBar_Back);
        TopBar_Back.setLayout(TopBar_BackLayout);
        TopBar_BackLayout.setHorizontalGroup(
            TopBar_BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
            .addGroup(TopBar_BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TopBar_BackLayout.createSequentialGroup()
                    .addGap(426, 426, 426)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(426, Short.MAX_VALUE)))
        );
        TopBar_BackLayout.setVerticalGroup(
            TopBar_BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBar_BackLayout.createSequentialGroup()
                .addComponent(TopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(TopBar_BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TopBar_BackLayout.createSequentialGroup()
                    .addGap(138, 138, 138)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(52, Short.MAX_VALUE)))
        );

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(70);
        panelRound2.setRoundTopLeft(70);

        panelRound1.setBackground(new java.awt.Color(204, 255, 204));
        panelRound1.setRoundBottomLeft(60);
        panelRound1.setRoundTopLeft(60);
        panelRound1.setLayout(null);

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(60);
        panelRound3.setRoundBottomRight(60);
        panelRound3.setRoundTopLeft(60);
        panelRound3.setRoundTopRight(60);

        Profile_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Profile_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/1Admin.png"))); // NOI18N

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Profile_Image))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Profile_Image))
        );

        panelRound1.add(panelRound3);
        panelRound3.setBounds(0, 0, 60, 60);

        username.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        username.setForeground(new java.awt.Color(72, 100, 114));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Username");
        panelRound1.add(username);
        username.setBounds(70, 0, 90, 30);

        usertype.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        usertype.setForeground(new java.awt.Color(72, 100, 114));
        usertype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usertype.setText("Admin");
        panelRound1.add(usertype);
        usertype.setBounds(70, 30, 90, 20);

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        SideMenuBar_Back.setBackground(new java.awt.Color(232, 244, 233));
        SideMenuBar_Back.setMaximumSize(new java.awt.Dimension(228, 495));
        SideMenuBar_Back.setMinimumSize(new java.awt.Dimension(228, 495));
        SideMenuBar_Back.setPreferredSize(new java.awt.Dimension(228, 495));

        SideMenuBar.setBackground(new java.awt.Color(255, 255, 255));
        SideMenuBar.setMaximumSize(new java.awt.Dimension(223, 495));
        SideMenuBar.setMinimumSize(new java.awt.Dimension(223, 495));
        SideMenuBar.setPreferredSize(new java.awt.Dimension(223, 495));

        pharm.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        pharm.setForeground(new java.awt.Color(72, 100, 114));
        pharm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pharm.setText("Pharmacist Details");
        pharm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pharm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pharmMouseClicked(evt);
            }
        });

        doctor.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        doctor.setForeground(new java.awt.Color(72, 100, 114));
        doctor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        doctor.setText("Doctor Details   ");
        doctor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorMouseClicked(evt);
            }
        });

        pet.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        pet.setForeground(new java.awt.Color(72, 100, 114));
        pet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pet.setText("Pet Details ");
        pet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                petMouseClicked(evt);
            }
        });

        recept.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        recept.setForeground(new java.awt.Color(72, 100, 114));
        recept.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        recept.setText("Receptionist Details");
        recept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receptMouseClicked(evt);
            }
        });

        LogOut.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        LogOut.setForeground(new java.awt.Color(72, 100, 114));
        LogOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LogOut.setText("Log out");
        LogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut.setPreferredSize(new java.awt.Dimension(87, 19));
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
        });

        PAI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_pets_25px_2.png"))); // NOI18N
        PAI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PAI.setPreferredSize(new java.awt.Dimension(34, 34));
        PAI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PAIMouseClicked(evt);
            }
        });

        PHI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_doctors_bag_25px.png"))); // NOI18N
        PHI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PHI.setPreferredSize(new java.awt.Dimension(34, 34));
        PHI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PHIMouseClicked(evt);
            }
        });

        REI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_reception_25px_2.png"))); // NOI18N
        REI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        REI.setPreferredSize(new java.awt.Dimension(34, 34));
        REI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REIMouseClicked(evt);
            }
        });

        LOI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_logout_rounded_left_25px_2.png"))); // NOI18N
        LOI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOI.setPreferredSize(new java.awt.Dimension(34, 34));
        LOI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOIMouseClicked(evt);
            }
        });

        DOI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_stethoscope_25px_2.png"))); // NOI18N
        DOI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DOI.setPreferredSize(new java.awt.Dimension(34, 34));
        DOI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DOIMouseClicked(evt);
            }
        });

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/dr_pet.png"))); // NOI18N
        Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(72, 100, 114));
        jLabel1.setText("Main Menu");

        javax.swing.GroupLayout SideMenuBarLayout = new javax.swing.GroupLayout(SideMenuBar);
        SideMenuBar.setLayout(SideMenuBarLayout);
        SideMenuBarLayout.setHorizontalGroup(
            SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideMenuBarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideMenuBarLayout.createSequentialGroup()
                        .addGroup(SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PAI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DOI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PHI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(REI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LOI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(recept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pharm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        SideMenuBarLayout.setVerticalGroup(
            SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideMenuBarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PAI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PHI, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pharm, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recept, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LOI, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout SideMenuBar_BackLayout = new javax.swing.GroupLayout(SideMenuBar_Back);
        SideMenuBar_Back.setLayout(SideMenuBar_BackLayout);
        SideMenuBar_BackLayout.setHorizontalGroup(
            SideMenuBar_BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideMenuBar_BackLayout.createSequentialGroup()
                .addComponent(SideMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );
        SideMenuBar_BackLayout.setVerticalGroup(
            SideMenuBar_BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideMenuBar_BackLayout.createSequentialGroup()
                .addComponent(SideMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        doc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Doctor ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        doc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(doc);

        pet_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Pet ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        pet_table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pet_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pet_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pet_table);

        panelRound6.setBackground(new java.awt.Color(222, 237, 223));
        panelRound6.setMaximumSize(new java.awt.Dimension(175, 85));
        panelRound6.setMinimumSize(new java.awt.Dimension(175, 85));
        panelRound6.setRoundBottomLeft(25);
        panelRound6.setRoundBottomRight(25);
        panelRound6.setRoundTopLeft(25);
        panelRound6.setRoundTopRight(25);

        panelRound22.setBackground(new java.awt.Color(111, 225, 119));
        panelRound22.setMaximumSize(new java.awt.Dimension(170, 80));
        panelRound22.setMinimumSize(new java.awt.Dimension(170, 80));
        panelRound22.setRoundBottomLeft(25);
        panelRound22.setRoundBottomRight(25);
        panelRound22.setRoundTopLeft(25);
        panelRound22.setRoundTopRight(25);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Total Doctors");
        jLabel3.setMaximumSize(new java.awt.Dimension(79, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(79, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(79, 25));

        d_count.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        d_count.setForeground(new java.awt.Color(255, 255, 255));
        d_count.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        d_count.setText("00");
        d_count.setMaximumSize(new java.awt.Dimension(20, 20));
        d_count.setMinimumSize(new java.awt.Dimension(20, 20));
        d_count.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_veterinarian_male_40px_1.png"))); // NOI18N

        javax.swing.GroupLayout panelRound22Layout = new javax.swing.GroupLayout(panelRound22);
        panelRound22.setLayout(panelRound22Layout);
        panelRound22Layout.setHorizontalGroup(
            panelRound22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound22Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelRound22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d_count, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );
        panelRound22Layout.setVerticalGroup(
            panelRound22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRound22Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addComponent(panelRound22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addComponent(panelRound22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        panelRound13.setBackground(new java.awt.Color(222, 237, 223));
        panelRound13.setMaximumSize(new java.awt.Dimension(175, 85));
        panelRound13.setMinimumSize(new java.awt.Dimension(175, 85));
        panelRound13.setRoundBottomLeft(25);
        panelRound13.setRoundBottomRight(25);
        panelRound13.setRoundTopLeft(25);
        panelRound13.setRoundTopRight(25);

        panelRound24.setBackground(new java.awt.Color(125, 181, 242));
        panelRound24.setMaximumSize(new java.awt.Dimension(170, 80));
        panelRound24.setMinimumSize(new java.awt.Dimension(170, 80));
        panelRound24.setRoundBottomLeft(25);
        panelRound24.setRoundBottomRight(25);
        panelRound24.setRoundTopLeft(25);
        panelRound24.setRoundTopRight(25);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Total Pharmacists");
        jLabel6.setMaximumSize(new java.awt.Dimension(79, 25));
        jLabel6.setMinimumSize(new java.awt.Dimension(79, 25));
        jLabel6.setPreferredSize(new java.awt.Dimension(79, 25));

        ph_count.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        ph_count.setForeground(new java.awt.Color(255, 255, 255));
        ph_count.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ph_count.setText("00");
        ph_count.setMaximumSize(new java.awt.Dimension(20, 20));
        ph_count.setMinimumSize(new java.awt.Dimension(20, 20));
        ph_count.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_pharmacist_40px.png"))); // NOI18N

        javax.swing.GroupLayout panelRound24Layout = new javax.swing.GroupLayout(panelRound24);
        panelRound24.setLayout(panelRound24Layout);
        panelRound24Layout.setHorizontalGroup(
            panelRound24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound24Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelRound24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound24Layout.createSequentialGroup()
                        .addComponent(ph_count, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 132, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRound24Layout.setVerticalGroup(
            panelRound24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound24Layout.createSequentialGroup()
                .addGroup(panelRound24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound24Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ph_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound24Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel31)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRound13Layout = new javax.swing.GroupLayout(panelRound13);
        panelRound13.setLayout(panelRound13Layout);
        panelRound13Layout.setHorizontalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound13Layout.createSequentialGroup()
                .addComponent(panelRound24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        panelRound13Layout.setVerticalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound13Layout.createSequentialGroup()
                .addComponent(panelRound24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        panelRound15.setBackground(new java.awt.Color(222, 237, 223));
        panelRound15.setMaximumSize(new java.awt.Dimension(175, 85));
        panelRound15.setMinimumSize(new java.awt.Dimension(175, 85));
        panelRound15.setRoundBottomLeft(25);
        panelRound15.setRoundBottomRight(25);
        panelRound15.setRoundTopLeft(25);
        panelRound15.setRoundTopRight(25);

        panelRound26.setBackground(new java.awt.Color(181, 123, 240));
        panelRound26.setMaximumSize(new java.awt.Dimension(170, 80));
        panelRound26.setMinimumSize(new java.awt.Dimension(170, 80));
        panelRound26.setRoundBottomLeft(25);
        panelRound26.setRoundBottomRight(25);
        panelRound26.setRoundTopLeft(25);
        panelRound26.setRoundTopRight(25);

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Total Appointments ");
        jLabel26.setMaximumSize(new java.awt.Dimension(79, 25));
        jLabel26.setMinimumSize(new java.awt.Dimension(79, 25));
        jLabel26.setPreferredSize(new java.awt.Dimension(79, 25));

        channe_count.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        channe_count.setForeground(new java.awt.Color(255, 255, 255));
        channe_count.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        channe_count.setText("00");
        channe_count.setMaximumSize(new java.awt.Dimension(20, 20));
        channe_count.setMinimumSize(new java.awt.Dimension(20, 20));
        channe_count.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_appointment_scheduling_40px_1.png"))); // NOI18N

        javax.swing.GroupLayout panelRound26Layout = new javax.swing.GroupLayout(panelRound26);
        panelRound26.setLayout(panelRound26Layout);
        panelRound26Layout.setHorizontalGroup(
            panelRound26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound26Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelRound26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(channe_count, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addGap(15, 15, 15))
        );
        panelRound26Layout.setVerticalGroup(
            panelRound26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRound26Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(channe_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout panelRound15Layout = new javax.swing.GroupLayout(panelRound15);
        panelRound15.setLayout(panelRound15Layout);
        panelRound15Layout.setHorizontalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound15Layout.createSequentialGroup()
                .addComponent(panelRound26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        panelRound15Layout.setVerticalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound15Layout.createSequentialGroup()
                .addComponent(panelRound26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        panelRound12.setBackground(new java.awt.Color(222, 237, 223));
        panelRound12.setMaximumSize(new java.awt.Dimension(175, 85));
        panelRound12.setMinimumSize(new java.awt.Dimension(175, 85));
        panelRound12.setRoundBottomLeft(25);
        panelRound12.setRoundBottomRight(25);
        panelRound12.setRoundTopLeft(25);
        panelRound12.setRoundTopRight(25);

        panelRound23.setBackground(new java.awt.Color(252, 119, 115));
        panelRound23.setMaximumSize(new java.awt.Dimension(170, 80));
        panelRound23.setMinimumSize(new java.awt.Dimension(170, 80));
        panelRound23.setRoundBottomLeft(25);
        panelRound23.setRoundBottomRight(25);
        panelRound23.setRoundTopLeft(25);
        panelRound23.setRoundTopRight(25);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Total Pets");
        jLabel5.setMaximumSize(new java.awt.Dimension(79, 25));
        jLabel5.setMinimumSize(new java.awt.Dimension(79, 25));
        jLabel5.setPreferredSize(new java.awt.Dimension(79, 25));

        p_count.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        p_count.setForeground(new java.awt.Color(255, 255, 255));
        p_count.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        p_count.setText("00");
        p_count.setMaximumSize(new java.awt.Dimension(20, 20));
        p_count.setMinimumSize(new java.awt.Dimension(20, 20));
        p_count.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_puppy_40px_1.png"))); // NOI18N

        javax.swing.GroupLayout panelRound23Layout = new javax.swing.GroupLayout(panelRound23);
        panelRound23.setLayout(panelRound23Layout);
        panelRound23Layout.setHorizontalGroup(
            panelRound23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound23Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelRound23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_count, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound23Layout.setVerticalGroup(
            panelRound23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRound23Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRound12Layout = new javax.swing.GroupLayout(panelRound12);
        panelRound12.setLayout(panelRound12Layout);
        panelRound12Layout.setHorizontalGroup(
            panelRound12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound12Layout.createSequentialGroup()
                .addComponent(panelRound23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        panelRound12Layout.setVerticalGroup(
            panelRound12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound12Layout.createSequentialGroup()
                .addComponent(panelRound23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        panelRound14.setBackground(new java.awt.Color(222, 237, 223));
        panelRound14.setMaximumSize(new java.awt.Dimension(175, 85));
        panelRound14.setMinimumSize(new java.awt.Dimension(175, 85));
        panelRound14.setRoundBottomLeft(25);
        panelRound14.setRoundBottomRight(25);
        panelRound14.setRoundTopLeft(25);
        panelRound14.setRoundTopRight(25);

        panelRound25.setBackground(new java.awt.Color(255, 204, 102));
        panelRound25.setMaximumSize(new java.awt.Dimension(170, 80));
        panelRound25.setMinimumSize(new java.awt.Dimension(170, 80));
        panelRound25.setRoundBottomLeft(25);
        panelRound25.setRoundBottomRight(25);
        panelRound25.setRoundTopLeft(25);
        panelRound25.setRoundTopRight(25);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Total Receptionists");
        jLabel13.setMaximumSize(new java.awt.Dimension(79, 25));
        jLabel13.setMinimumSize(new java.awt.Dimension(79, 25));
        jLabel13.setPreferredSize(new java.awt.Dimension(79, 25));

        r_count.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        r_count.setForeground(new java.awt.Color(255, 255, 255));
        r_count.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        r_count.setText("00");
        r_count.setMaximumSize(new java.awt.Dimension(20, 20));
        r_count.setMinimumSize(new java.awt.Dimension(20, 20));
        r_count.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_reception_40px_1.png"))); // NOI18N

        javax.swing.GroupLayout panelRound25Layout = new javax.swing.GroupLayout(panelRound25);
        panelRound25.setLayout(panelRound25Layout);
        panelRound25Layout.setHorizontalGroup(
            panelRound25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound25Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelRound25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound25Layout.createSequentialGroup()
                        .addComponent(r_count, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 121, Short.MAX_VALUE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addGap(23, 23, 23))
        );
        panelRound25Layout.setVerticalGroup(
            panelRound25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound25Layout.createSequentialGroup()
                .addGroup(panelRound25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound25Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(r_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound25Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel30)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRound14Layout = new javax.swing.GroupLayout(panelRound14);
        panelRound14.setLayout(panelRound14Layout);
        panelRound14Layout.setHorizontalGroup(
            panelRound14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound14Layout.createSequentialGroup()
                .addComponent(panelRound25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        panelRound14Layout.setVerticalGroup(
            panelRound14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound14Layout.createSequentialGroup()
                .addComponent(panelRound25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        rec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        rec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(rec);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/paro.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/ani1.png"))); // NOI18N

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(SideMenuBar_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelRound12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(panelRound14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelRound13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 26, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(20, 20, 20))
                            .addComponent(TopBar_Back, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                        .addComponent(panelRound15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(286, Short.MAX_VALUE))))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideMenuBar_Back, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(TopBar_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelRound6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRound14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelRound13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelRound12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(panelRound15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Channel No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        cha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(cha);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(584, 584, 584)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(585, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(121, 121, 121)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(554, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(1200, 675));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniMouseClicked
        // Minimize:
        this.setExtendedState(Admin_Dashboard.ICONIFIED);
    }//GEN-LAST:event_MiniMouseClicked

    private void MaxiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaxiMouseClicked
        // Maximize:
        if(this.getExtendedState()!=Admin_Dashboard.MAXIMIZED_BOTH){
            this.setExtendedState(Admin_Dashboard.MAXIMIZED_BOTH);
        }
        else{
            this.setExtendedState(Admin_Dashboard.NORMAL);
        }
    }//GEN-LAST:event_MaxiMouseClicked

    private void CrossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrossMouseClicked
        super.dispose(); //exit 
    }//GEN-LAST:event_CrossMouseClicked

    private void LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseClicked
    }//GEN-LAST:event_LogoMouseClicked

    private void doctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorMouseClicked
        // TODO add your handling code here:
        new AD_Doctor_Details(uname).setVisible(true); //next interface
       super.dispose();
   
    }//GEN-LAST:event_doctorMouseClicked

    private void DOIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOIMouseClicked
             new AD_Doctor_Details(uname).setVisible(true); //next interface
    super.dispose();
    }//GEN-LAST:event_DOIMouseClicked

    private void petMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petMouseClicked
        new AD_Patient_Details(uname).setVisible(true);  //next interface
        super.dispose();
    }//GEN-LAST:event_petMouseClicked

    private void PAIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAIMouseClicked
        new AD_Patient_Details(uname).setVisible(true); //next interface
        super.dispose();
    }//GEN-LAST:event_PAIMouseClicked

    private void pharmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pharmMouseClicked
       new AD_Pharmacist_Details(uname).setVisible(true); //next interface
        super.dispose();
    }//GEN-LAST:event_pharmMouseClicked

    private void PHIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PHIMouseClicked

        new AD_Pharmacist_Details(uname).setVisible(true); //next interface
        super.dispose();
    }//GEN-LAST:event_PHIMouseClicked

    private void receptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receptMouseClicked
        new AD_Receptionist_Detail(uname).setVisible(true); //next interface
        super.dispose();
    }//GEN-LAST:event_receptMouseClicked

    private void REIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REIMouseClicked
        
        new AD_Receptionist_Detail(uname).setVisible(true); //next interface
        super.dispose();
    }//GEN-LAST:event_REIMouseClicked

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        // TODO add your handling code here:
        new Login_user_type().setVisible(true); //next interface
        super.dispose();
    }//GEN-LAST:event_LogOutMouseClicked

    private void LOIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOIMouseClicked
        // TODO add your handling code here:
        new Login_user_type().setVisible(true); //next interface
        super.dispose();
    }//GEN-LAST:event_LOIMouseClicked

    private void docMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_docMouseClicked

    private void pet_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pet_tableMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_pet_tableMouseClicked

    private void recMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_recMouseClicked

    private void phaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phaMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_phaMouseClicked

    private void chaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chaMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_chaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    String username = null;
                new Admin_Dashboard(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Cross;
    private javax.swing.JLabel DASHI;
    private javax.swing.JLabel DOI;
    private javax.swing.JLabel Dashboard;
    private javax.swing.JLabel LOI;
    private javax.swing.JLabel LogOut;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Maxi;
    private javax.swing.JLabel Mini;
    private javax.swing.JLabel PAI;
    private javax.swing.JLabel PHI;
    private javax.swing.JLabel Profile_Image;
    private javax.swing.JLabel REI;
    private javax.swing.JPanel SideMenuBar;
    private javax.swing.JPanel SideMenuBar_Back;
    private javax.swing.JPanel TopBar;
    private javax.swing.JPanel TopBar_Back;
    private javax.swing.JTable cha;
    private javax.swing.JLabel channe_count;
    private javax.swing.JLabel d_count;
    private javax.swing.JTable doc;
    private javax.swing.JLabel doctor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel p_count;
    private Design.PanelRound panelRound1;
    private Design.PanelRound panelRound12;
    private Design.PanelRound panelRound13;
    private Design.PanelRound panelRound14;
    private Design.PanelRound panelRound15;
    private Design.PanelRound panelRound2;
    private Design.PanelRound panelRound22;
    private Design.PanelRound panelRound23;
    private Design.PanelRound panelRound24;
    private Design.PanelRound panelRound25;
    private Design.PanelRound panelRound26;
    private Design.PanelRound panelRound3;
    private Design.PanelRound panelRound6;
    private javax.swing.JLabel pet;
    private javax.swing.JTable pet_table;
    private javax.swing.JLabel ph_count;
    private javax.swing.JTable pha;
    private javax.swing.JLabel pharm;
    private javax.swing.JLabel r_count;
    private javax.swing.JTable rec;
    private javax.swing.JLabel recept;
    private javax.swing.JLabel username;
    private javax.swing.JLabel usertype;
    // End of variables declaration//GEN-END:variables
}
