/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Pharmacist;


import Control.bill_create_controller;
import Control.prescription_searchController;
import Model.DBConnection;
import Model.Drug_Searchtable;
import Model.prescription_searchtable;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.geom.RoundRectangle2D;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Deshan Asanka
 */
public class bill extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Dashboard
     */
 
    public bill() {
        initComponents();
        
        setBackground(new Color(1.0f,1.0f,1.0f,0.8f));   
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 35, 35));
        
        
              
        ResultSet n = new Drug_Searchtable().searchdrug();
        DefaultTableModel xtm;
        xtm = (DefaultTableModel) drug_table.getModel();
        xtm.setRowCount(0); //sets the number of rows in the model
        try{
            Vector v;
            while (n.next()){
                v = new Vector();
                v.add(n.getString("id"));
                v.add(n.getString("name"));
                v.add(n.getString("price"));
             

                xtm.addRow(v);

                //Adds a row to the end of the model
            }
            DBConnection.closeCon();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        
        //---------------------------
        
               
    }
    

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void print(){
      
        txtprint.setText(txtprint.getText()+"----------------------------------------------------------------------------------------------------------------------------------\n");
        txtprint.setText(txtprint.getText()+"\t\t    Dr.Pet Pharmacy" +"\n");
        txtprint.setText(txtprint.getText()+"\t\t              Invoice" +"\n");
        txtprint.setText(txtprint.getText()+"----------------------------------------------------------------------------------------------------------------------------------\n");
        DefaultTableModel model = (DefaultTableModel)bill_table.getModel();
        txtprint.setText(txtprint.getText()+"Qty"+"\t"+"ID"+"\t"+"Name"+"\t"+"\t"+"1tb/price"+"\t"+"Price"+"\n");
        for(int i = 0; i<bill_table.getRowCount();i++){
            String Quantity = bill_table.getValueAt(i, 0).toString() ;
            String id = bill_table.getValueAt(i, 1).toString() ;
            String name = bill_table.getValueAt(i,2).toString() ;
            String tbprice = bill_table.getValueAt(i, 3).toString() ;
            String price = bill_table.getValueAt(i, 4).toString() ;
        txtprint.setText(txtprint.getText()+Quantity+"\t"+id+"\t"+name+"\t"+"\t"+tbprice+"\t"+price+"\n");    
        }
        txtprint.setText(txtprint.getText()+"\n----------------------------------------------------------------------------------------------------------------------------------\n");
        txtprint.setText(txtprint.getText()+"Total"+"\t"+"\t"+"\t"+"\t"+"\t"+total1+"\n");    
        txtprint.setText(txtprint.getText()+"\n=========================================================================\n");
        txtprint.setText(txtprint.getText()+"\t\tThank You! Come Again" +"\n");
        txtprint.setText(txtprint.getText()+"\n                                                   ***********************                                                \n");
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound5 = new Design.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelRound4 = new Design.PanelRound();
        panelRound7 = new Design.PanelRound();
        username = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        id = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        contactno = new javax.swing.JTextField();
        NIC = new javax.swing.JTextField();
        roomno = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        specialization = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        panelRound14 = new Design.PanelRound();
        panelRound15 = new Design.PanelRound();
        jTextField1 = new javax.swing.JTextField();
        Cross = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Idtxt = new javax.swing.JTextField();
        panelRound6 = new Design.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        panelRound24 = new Design.PanelRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        pres_table = new javax.swing.JTable();
        edit = new Design.PanelRound();
        edit1 = new javax.swing.JLabel();
        Dashboard1 = new javax.swing.JLabel();
        back = new Design.PanelRound();
        backtxt = new javax.swing.JLabel();
        back1 = new Design.PanelRound();
        backtxt1 = new javax.swing.JLabel();
        billno = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        panelRound18 = new Design.PanelRound();
        panelRound19 = new Design.PanelRound();
        jScrollPane4 = new javax.swing.JScrollPane();
        drug_table = new javax.swing.JTable();
        tb_price = new javax.swing.JTextField();
        Dashboard2 = new javax.swing.JLabel();
        name_drug = new javax.swing.JTextField();
        panelRound16 = new Design.PanelRound();
        panelRound17 = new Design.PanelRound();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtprint = new javax.swing.JTextArea();
        date = new com.toedter.calendar.JDateChooser();
        panelRound22 = new Design.PanelRound();
        panelRound23 = new Design.PanelRound();
        jScrollPane6 = new javax.swing.JScrollPane();
        bill_table = new javax.swing.JTable();
        qty = new javax.swing.JTextField();
        edit5 = new Design.PanelRound();
        add = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        edit4 = new Design.PanelRound();
        create = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        price1 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        dr_id = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        edit6 = new Design.PanelRound();
        print = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        Dashboard = new javax.swing.JLabel();
        DASHI = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        panelRound5.setBackground(new java.awt.Color(39, 212, 59));
        panelRound5.setRoundBottomLeft(15);
        panelRound5.setRoundBottomRight(15);
        panelRound5.setRoundTopLeft(15);
        panelRound5.setRoundTopRight(15);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel7.setText("Doctor ID :");

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel16.setText("Gender :");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADD");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CANCEL");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        panelRound4.setBackground(new java.awt.Color(193, 193, 193));
        panelRound4.setRoundBottomLeft(15);
        panelRound4.setRoundBottomRight(15);
        panelRound4.setRoundTopLeft(15);
        panelRound4.setRoundTopRight(15);

        panelRound7.setBackground(new java.awt.Color(39, 212, 59));
        panelRound7.setRoundBottomLeft(15);
        panelRound7.setRoundBottomRight(15);
        panelRound7.setRoundTopLeft(15);
        panelRound7.setRoundTopRight(15);

        username.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel17.setText("Password :");

        password.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        id.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        year.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        year.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        name.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        contactno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        contactno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        contactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnoActionPerformed(evt);
            }
        });

        NIC.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        NIC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        roomno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        roomno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        male.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        male.setText("Male");
        male.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        female.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        female.setText("Female");
        female.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        specialization.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        specialization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anesthesia", "Animal Welfare", "Behavior", "Dentistry", "Dermatology", "Oncology", "Microbiology", "Nutrition", "Ophthalmology", "Pathology", "Radiology", "Surgery", "Theriogenology" }));
        specialization.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel14.setText("Username :");

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel12.setText("Contact No:");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel13.setText("Room No :");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel11.setText("Years of Experience :");

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel18.setText("Specialization :");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel9.setText("NIC N0 :");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel8.setText("Doctor Name :");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/ADD POP.png"))); // NOI18N
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelRound14.setBackground(new java.awt.Color(222, 237, 223));
        panelRound14.setMaximumSize(new java.awt.Dimension(275, 85));
        panelRound14.setMinimumSize(new java.awt.Dimension(275, 85));
        panelRound14.setRoundBottomLeft(25);
        panelRound14.setRoundBottomRight(25);
        panelRound14.setRoundTopLeft(25);
        panelRound14.setRoundTopRight(25);

        panelRound15.setBackground(new java.awt.Color(255, 255, 255));
        panelRound15.setMaximumSize(new java.awt.Dimension(270, 165));
        panelRound15.setMinimumSize(new java.awt.Dimension(270, 165));
        panelRound15.setRoundBottomLeft(25);
        panelRound15.setRoundBottomRight(25);
        panelRound15.setRoundTopLeft(25);
        panelRound15.setRoundTopRight(25);

        jTextField1.setBackground(new java.awt.Color(204, 255, 204));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound15Layout = new javax.swing.GroupLayout(panelRound15);
        panelRound15.setLayout(panelRound15Layout);
        panelRound15Layout.setHorizontalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound15Layout.setVerticalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelRound14Layout = new javax.swing.GroupLayout(panelRound14);
        panelRound14.setLayout(panelRound14Layout);
        panelRound14Layout.setHorizontalGroup(
            panelRound14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound14Layout.createSequentialGroup()
                .addComponent(panelRound15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound14Layout.setVerticalGroup(
            panelRound14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound14Layout.createSequentialGroup()
                .addComponent(panelRound15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        Cross.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cross.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/Cross.png"))); // NOI18N
        Cross.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cross.setPreferredSize(new java.awt.Dimension(25, 25));
        Cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrossMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1328, 747));
        setMinimumSize(new java.awt.Dimension(1328, 747));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1328, 747));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Enter Prescriptions ID:");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(560, 80, 190, 26);

        Idtxt.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdtxtActionPerformed(evt);
            }
        });
        getContentPane().add(Idtxt);
        Idtxt.setBounds(760, 80, 100, 30);

        panelRound6.setBackground(new java.awt.Color(39, 212, 59));
        panelRound6.setRoundBottomLeft(15);
        panelRound6.setRoundBottomRight(15);
        panelRound6.setRoundTopLeft(15);
        panelRound6.setRoundTopRight(15);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("View");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        getContentPane().add(panelRound6);
        panelRound6.setBounds(910, 80, 90, 30);

        panelRound24.setBackground(new java.awt.Color(255, 255, 255));
        panelRound24.setMaximumSize(new java.awt.Dimension(270, 165));
        panelRound24.setMinimumSize(new java.awt.Dimension(270, 165));
        panelRound24.setRoundBottomLeft(25);
        panelRound24.setRoundBottomRight(25);
        panelRound24.setRoundTopLeft(25);
        panelRound24.setRoundTopRight(25);

        pres_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prescription Id", "Desease type", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        pres_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pres_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pres_table);
        if (pres_table.getColumnModel().getColumnCount() > 0) {
            pres_table.getColumnModel().getColumn(0).setMinWidth(90);
            pres_table.getColumnModel().getColumn(0).setPreferredWidth(90);
            pres_table.getColumnModel().getColumn(0).setMaxWidth(90);
            pres_table.getColumnModel().getColumn(1).setMinWidth(100);
            pres_table.getColumnModel().getColumn(1).setPreferredWidth(100);
            pres_table.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        javax.swing.GroupLayout panelRound24Layout = new javax.swing.GroupLayout(panelRound24);
        panelRound24.setLayout(panelRound24Layout);
        panelRound24Layout.setHorizontalGroup(
            panelRound24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound24Layout.setVerticalGroup(
            panelRound24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        getContentPane().add(panelRound24);
        panelRound24.setBounds(550, 110, 740, 70);

        edit.setBackground(new java.awt.Color(39, 212, 59));
        edit.setRoundBottomLeft(15);
        edit.setRoundBottomRight(15);
        edit.setRoundTopLeft(15);
        edit.setRoundTopRight(15);
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });

        edit1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        edit1.setForeground(new java.awt.Color(255, 255, 255));
        edit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit1.setText("Edit");
        edit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit1MouseClicked(evt);
            }
        });
        edit.add(edit1);

        getContentPane().add(edit);
        edit.setBounds(553, 835, 115, 33);

        Dashboard1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        Dashboard1.setForeground(new java.awt.Color(96, 125, 139));
        Dashboard1.setText("Bill");
        getContentPane().add(Dashboard1);
        Dashboard1.setBounds(80, 430, 140, 31);

        back.setBackground(new java.awt.Color(204, 204, 204));
        back.setRoundBottomLeft(15);
        back.setRoundBottomRight(15);
        back.setRoundTopLeft(15);
        back.setRoundTopRight(15);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        backtxt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        backtxt.setForeground(new java.awt.Color(255, 255, 255));
        backtxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backtxt.setText("Back");
        backtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backtxtMouseClicked(evt);
            }
        });
        back.add(backtxt);

        getContentPane().add(back);
        back.setBounds(85, 835, 115, 33);

        back1.setBackground(new java.awt.Color(153, 153, 153));
        back1.setRoundBottomLeft(15);
        back1.setRoundBottomRight(15);
        back1.setRoundTopLeft(15);
        back1.setRoundTopRight(15);
        back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back1MouseClicked(evt);
            }
        });

        backtxt1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        backtxt1.setForeground(new java.awt.Color(255, 255, 255));
        backtxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backtxt1.setText("Back");
        backtxt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backtxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backtxt1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout back1Layout = new javax.swing.GroupLayout(back1);
        back1.setLayout(back1Layout);
        back1Layout.setHorizontalGroup(
            back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backtxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );
        back1Layout.setVerticalGroup(
            back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backtxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        getContentPane().add(back1);
        back1.setBounds(720, 660, 115, 33);

        billno.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        billno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        billno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billnoActionPerformed(evt);
            }
        });
        getContentPane().add(billno);
        billno.setBounds(810, 190, 220, 30);

        jLabel25.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel25.setText("Bill No:");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(660, 190, 110, 30);

        panelRound18.setBackground(new java.awt.Color(222, 237, 223));
        panelRound18.setMaximumSize(new java.awt.Dimension(275, 85));
        panelRound18.setMinimumSize(new java.awt.Dimension(275, 85));
        panelRound18.setRoundBottomLeft(25);
        panelRound18.setRoundBottomRight(25);
        panelRound18.setRoundTopLeft(25);
        panelRound18.setRoundTopRight(25);

        panelRound19.setBackground(new java.awt.Color(255, 255, 255));
        panelRound19.setMaximumSize(new java.awt.Dimension(270, 165));
        panelRound19.setMinimumSize(new java.awt.Dimension(270, 165));
        panelRound19.setRoundBottomLeft(25);
        panelRound19.setRoundBottomRight(25);
        panelRound19.setRoundTopLeft(25);
        panelRound19.setRoundTopRight(25);

        drug_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        drug_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drug_tableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(drug_table);

        javax.swing.GroupLayout panelRound19Layout = new javax.swing.GroupLayout(panelRound19);
        panelRound19.setLayout(panelRound19Layout);
        panelRound19Layout.setHorizontalGroup(
            panelRound19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound19Layout.setVerticalGroup(
            panelRound19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelRound18Layout = new javax.swing.GroupLayout(panelRound18);
        panelRound18.setLayout(panelRound18Layout);
        panelRound18Layout.setHorizontalGroup(
            panelRound18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound18Layout.createSequentialGroup()
                .addComponent(panelRound19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound18Layout.setVerticalGroup(
            panelRound18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound18Layout.createSequentialGroup()
                .addComponent(panelRound19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panelRound18);
        panelRound18.setBounds(80, 170, 470, 240);

        tb_price.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        tb_price.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(tb_price);
        tb_price.setBounds(1040, 320, 110, 36);

        Dashboard2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        Dashboard2.setForeground(new java.awt.Color(96, 125, 139));
        Dashboard2.setText("Drugs");
        getContentPane().add(Dashboard2);
        Dashboard2.setBounds(90, 140, 140, 20);

        name_drug.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        name_drug.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(name_drug);
        name_drug.setBounds(840, 320, 180, 30);

        panelRound16.setBackground(new java.awt.Color(222, 237, 223));
        panelRound16.setMaximumSize(new java.awt.Dimension(275, 85));
        panelRound16.setMinimumSize(new java.awt.Dimension(275, 85));
        panelRound16.setRoundBottomLeft(25);
        panelRound16.setRoundBottomRight(25);
        panelRound16.setRoundTopLeft(25);
        panelRound16.setRoundTopRight(25);

        panelRound17.setBackground(new java.awt.Color(255, 255, 255));
        panelRound17.setMaximumSize(new java.awt.Dimension(270, 165));
        panelRound17.setMinimumSize(new java.awt.Dimension(270, 165));
        panelRound17.setRoundBottomLeft(25);
        panelRound17.setRoundBottomRight(25);
        panelRound17.setRoundTopLeft(25);
        panelRound17.setRoundTopRight(25);

        txtprint.setColumns(20);
        txtprint.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtprint.setRows(5);
        txtprint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0), 2));
        jScrollPane3.setViewportView(txtprint);

        javax.swing.GroupLayout panelRound17Layout = new javax.swing.GroupLayout(panelRound17);
        panelRound17.setLayout(panelRound17Layout);
        panelRound17Layout.setHorizontalGroup(
            panelRound17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound17Layout.setVerticalGroup(
            panelRound17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelRound16Layout = new javax.swing.GroupLayout(panelRound16);
        panelRound16.setLayout(panelRound16Layout);
        panelRound16Layout.setHorizontalGroup(
            panelRound16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound16Layout.createSequentialGroup()
                .addComponent(panelRound17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        panelRound16Layout.setVerticalGroup(
            panelRound16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound16Layout.createSequentialGroup()
                .addComponent(panelRound17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        getContentPane().add(panelRound16);
        panelRound16.setBounds(650, 460, 620, 190);
        getContentPane().add(date);
        date.setBounds(810, 230, 220, 30);

        panelRound22.setBackground(new java.awt.Color(222, 237, 223));
        panelRound22.setMaximumSize(new java.awt.Dimension(275, 85));
        panelRound22.setMinimumSize(new java.awt.Dimension(275, 85));
        panelRound22.setRoundBottomLeft(25);
        panelRound22.setRoundBottomRight(25);
        panelRound22.setRoundTopLeft(25);
        panelRound22.setRoundTopRight(25);

        panelRound23.setBackground(new java.awt.Color(255, 255, 255));
        panelRound23.setMaximumSize(new java.awt.Dimension(270, 165));
        panelRound23.setMinimumSize(new java.awt.Dimension(270, 165));
        panelRound23.setRoundBottomLeft(25);
        panelRound23.setRoundBottomRight(25);
        panelRound23.setRoundTopLeft(25);
        panelRound23.setRoundTopRight(25);

        bill_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Qty", "Id", "Name", "1tb/price", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bill_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bill_tableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(bill_table);

        javax.swing.GroupLayout panelRound23Layout = new javax.swing.GroupLayout(panelRound23);
        panelRound23.setLayout(panelRound23Layout);
        panelRound23Layout.setHorizontalGroup(
            panelRound23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound23Layout.setVerticalGroup(
            panelRound23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRound22Layout = new javax.swing.GroupLayout(panelRound22);
        panelRound22.setLayout(panelRound22Layout);
        panelRound22Layout.setHorizontalGroup(
            panelRound22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound22Layout.createSequentialGroup()
                .addComponent(panelRound23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound22Layout.setVerticalGroup(
            panelRound22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound22Layout.createSequentialGroup()
                .addComponent(panelRound23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        getContentPane().add(panelRound22);
        panelRound22.setBounds(70, 460, 490, 230);

        qty.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        qty.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyKeyPressed(evt);
            }
        });
        getContentPane().add(qty);
        qty.setBounds(660, 320, 70, 30);

        edit5.setBackground(new java.awt.Color(15, 225, 111));
        edit5.setRoundBottomLeft(15);
        edit5.setRoundBottomRight(15);
        edit5.setRoundTopLeft(15);
        edit5.setRoundTopRight(15);
        edit5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit5MouseClicked(evt);
            }
        });

        add.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add.setText("Add");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout edit5Layout = new javax.swing.GroupLayout(edit5);
        edit5.setLayout(edit5Layout);
        edit5Layout.setHorizontalGroup(
            edit5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );
        edit5Layout.setVerticalGroup(
            edit5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        getContentPane().add(edit5);
        edit5.setBounds(920, 370, 115, 33);

        jLabel42.setFont(new java.awt.Font("Calibri", 1, 25)); // NOI18N
        jLabel42.setText("Total :");
        getContentPane().add(jLabel42);
        jLabel42.setBounds(660, 420, 90, 40);

        edit4.setBackground(new java.awt.Color(15, 225, 111));
        edit4.setRoundBottomLeft(15);
        edit4.setRoundBottomRight(15);
        edit4.setRoundTopLeft(15);
        edit4.setRoundTopRight(15);
        edit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit4MouseClicked(evt);
            }
        });

        create.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        create.setForeground(new java.awt.Color(255, 255, 255));
        create.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create.setText("Create");
        create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout edit4Layout = new javax.swing.GroupLayout(edit4);
        edit4.setLayout(edit4Layout);
        edit4Layout.setHorizontalGroup(
            edit4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit4Layout.createSequentialGroup()
                .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        edit4Layout.setVerticalGroup(
            edit4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(create, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        getContentPane().add(edit4);
        edit4.setBounds(1090, 660, 115, 33);

        jLabel44.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Price");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(1160, 290, 110, 30);

        price1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        price1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(price1);
        price1.setBounds(1160, 320, 110, 36);

        jLabel43.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel43.setText("ID");
        getContentPane().add(jLabel43);
        jLabel43.setBounds(770, 290, 30, 30);

        dr_id.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        dr_id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(dr_id);
        dr_id.setBounds(750, 320, 70, 30);

        total.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        total.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(total);
        total.setBounds(760, 420, 250, 40);

        jLabel40.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("1tb/Price");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(1040, 290, 110, 30);

        jLabel39.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel39.setText("Name");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(900, 290, 70, 30);

        jLabel38.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel38.setText("Qty");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(670, 290, 40, 30);

        edit6.setBackground(new java.awt.Color(15, 225, 111));
        edit6.setRoundBottomLeft(15);
        edit6.setRoundBottomRight(15);
        edit6.setRoundTopLeft(15);
        edit6.setRoundTopRight(15);
        edit6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit6MouseClicked(evt);
            }
        });

        print.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        print.setText("Print");
        print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout edit6Layout = new javax.swing.GroupLayout(edit6);
        edit6.setLayout(edit6Layout);
        edit6Layout.setHorizontalGroup(
            edit6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(print, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        edit6Layout.setVerticalGroup(
            edit6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(print, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        getContentPane().add(edit6);
        edit6.setBounds(900, 660, 120, 33);

        jLabel37.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel37.setText("Date :");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(660, 230, 120, 30);

        Dashboard.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(96, 125, 139));
        Dashboard.setText("Create Bill");
        getContentPane().add(Dashboard);
        Dashboard.setBounds(190, 80, 140, 31);

        DASHI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_fries_menu_30px_1.png"))); // NOI18N
        getContentPane().add(DASHI);
        DASHI.setBounds(150, 80, 30, 31);

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/edit22.png"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(1328, 747));
        background.setMinimumSize(new java.awt.Dimension(1328, 747));
        background.setPreferredSize(new java.awt.Dimension(1328, 747));
        getContentPane().add(background);
        background.setBounds(0, 0, 1328, 747);

        getAccessibleContext().setAccessibleDescription("");

        setSize(new java.awt.Dimension(1326, 747));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
    

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        // new pop_pass().setVisible(true);
      
    }//GEN-LAST:event_jLabel6MouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void contactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnoActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void edit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_edit1MouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
     // TODO add your handling code here:
    }//GEN-LAST:event_editMouseClicked

    private void backtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backtxtMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked

    }//GEN-LAST:event_backMouseClicked

    private void backtxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtxt1MouseClicked
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_backtxt1MouseClicked

    private void back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back1MouseClicked
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_back1MouseClicked

    private void billnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billnoActionPerformed

    private void createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseClicked
 SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        String Date = dateformat.format(date.getDate());
        int a = Integer.parseInt(total.getText());
        
        if (billno.getText().trim().isEmpty()|| total.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Add all the credentials", "Error" , JOptionPane.ERROR_MESSAGE);}
        else{
            bill_create_controller.Form(billno.getText(),Date,a);
print();

        }
    }//GEN-LAST:event_createMouseClicked

    private void edit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit4MouseClicked

    }//GEN-LAST:event_edit4MouseClicked

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        try {
            txtprint.print();
        } catch (PrinterException ex) {
            Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printMouseClicked

    private void edit6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_edit6MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void drug_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drug_tableMouseClicked
      DefaultTableModel d1 = (DefaultTableModel)drug_table.getModel() ;{
        int SelectIndex = drug_table.getSelectedRow();
        
        dr_id.setText(d1.getValueAt(SelectIndex, 0).toString());
        name_drug.setText(d1.getValueAt(SelectIndex, 1).toString());
        tb_price.setText(d1.getValueAt(SelectIndex, 2).toString());}
      

    }//GEN-LAST:event_drug_tableMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        DefaultTableModel df; 
        df = (DefaultTableModel)bill_table.getModel() ; 
        df.addRow(new String[]
        {qty.getText(),
            dr_id.getText(),
            name_drug.getText(),
            tb_price.getText(),
            price1.getText()});
        clearField();
    }//GEN-LAST:event_addMouseClicked

    private void edit5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_edit5MouseClicked

    private void bill_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bill_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bill_tableMouseClicked
int total1 = 0;
    private void qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyPressed
        char c = evt.getKeyChar();
if(Character.isLetter(c)){
  qty.setEditable(false);
   JOptionPane.showMessageDialog(null, "Please Enter Numbers only", "Error",JOptionPane.ERROR_MESSAGE);
  //contactno.setText("Please Enter Numbers only");
}
else
{
  qty.setEditable(true);   
  if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        int price;
        int quantity = Integer.parseInt(qty.getText());
        int tbp = Integer.parseInt(tb_price.getText()); 
        price = quantity * tbp; 
        
        total1 =total1 + price;
        price1.setText(String.valueOf(price));
        total.setText(String.valueOf(total1));
         }
} 

    }//GEN-LAST:event_qtyKeyPressed

    private void CrossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrossMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CrossMouseClicked

    private void pres_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pres_tableMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_pres_tableMouseClicked

    private void IdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdtxtActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if (Idtxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Add Prescription NO", "Error" , JOptionPane.ERROR_MESSAGE);}
        else{
            String channel_no =Idtxt.getText();
            prescription_searchController.Form(Idtxt.getText());

            ResultSet r = new prescription_searchtable().searchprescription(channel_no);
            DefaultTableModel dtm = (DefaultTableModel) pres_table.getModel();
            dtm.setRowCount(0);
            try{
                Vector v;
                while (r.next()){
                    v = new Vector();
                    v.add(r.getString("pres_id"));
                    v.add(r.getString("desease_type"));
                    v.add(r.getString("description"));

                    dtm.addRow(v);

                    //Adds a row to the end of the model
                }
                DBConnection.closeCon();
            }
            catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jLabel4MouseClicked


    /**
     * @param args the command line arguments
     */
public void clearField(){
dr_id.setText("");
name_drug.setText("");
tb_price.setText("");
qty.setText("");
price1.setText("");


}

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
      
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
      
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
      
        //</editor-fold>
        //</editor-fold>
      
 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cross;
    private javax.swing.JLabel DASHI;
    private javax.swing.JLabel Dashboard;
    private javax.swing.JLabel Dashboard1;
    private javax.swing.JLabel Dashboard2;
    private javax.swing.JTextField Idtxt;
    private javax.swing.JTextField NIC;
    private javax.swing.JLabel add;
    private Design.PanelRound back;
    private Design.PanelRound back1;
    private javax.swing.JLabel background;
    private javax.swing.JLabel backtxt;
    private javax.swing.JLabel backtxt1;
    private javax.swing.JTable bill_table;
    private javax.swing.JTextField billno;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField contactno;
    private javax.swing.JLabel create;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField dr_id;
    private javax.swing.JTable drug_table;
    private Design.PanelRound edit;
    private javax.swing.JLabel edit1;
    private Design.PanelRound edit4;
    private Design.PanelRound edit5;
    private Design.PanelRound edit6;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name_drug;
    private Design.PanelRound panelRound14;
    private Design.PanelRound panelRound15;
    private Design.PanelRound panelRound16;
    private Design.PanelRound panelRound17;
    private Design.PanelRound panelRound18;
    private Design.PanelRound panelRound19;
    private Design.PanelRound panelRound22;
    private Design.PanelRound panelRound23;
    private Design.PanelRound panelRound24;
    private Design.PanelRound panelRound4;
    private Design.PanelRound panelRound5;
    private Design.PanelRound panelRound6;
    private Design.PanelRound panelRound7;
    private javax.swing.JPasswordField password;
    private javax.swing.JTable pres_table;
    private javax.swing.JTextField price1;
    private javax.swing.JLabel print;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField roomno;
    private javax.swing.JComboBox<String> specialization;
    private javax.swing.JTextField tb_price;
    private javax.swing.JTextField total;
    private javax.swing.JTextArea txtprint;
    private javax.swing.JTextField username;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
