/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Receptionist;

import Model.Channel_Search;
import Model.DBConnection;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Deshan Asanka
 */
public class Channel extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Dashboard
     */
    String uname;
    public Channel(String user_name) {
        initComponents();
  this.uname = user_name;
        jLabel15.setText(uname);
        
        ResultSet r = new Channel_Search().searchChannel();
DefaultTableModel dtm = (DefaultTableModel) c_table.getModel();
dtm.setRowCount(0); //sets the number of rows in the model
try{
Vector v;
while (r.next()){
v = new Vector();
v.add(r.getString("channel_no"));
v.add(r.getString("dr_name"));
v.add(r.getString("pet_name"));
v.add(r.getString("room_no"));
v.add(r.getString("date"));
v.add(r.getString("channel_fee"));



dtm.addRow(v);

//Adds a row to the end of the model
}
DBConnection.closeCon();
}
catch (Exception e) {
e.printStackTrace();
}
int ch_count = c_table.getRowCount(); 
  channel.setText(String.valueOf(ch_count));

    }
    

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound5 = new Design.PanelRound();
        Background = new javax.swing.JPanel();
        panelRound2 = new Design.PanelRound();
        panelRound1 = new Design.PanelRound();
        panelRound3 = new Design.PanelRound();
        Profile_Image = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TopBar_Back = new javax.swing.JPanel();
        TopBar = new javax.swing.JPanel();
        Maxi = new javax.swing.JLabel();
        Mini = new javax.swing.JLabel();
        Cross = new javax.swing.JLabel();
        DASHI = new javax.swing.JLabel();
        Dashboard = new javax.swing.JLabel();
        SideMenuBar_Back = new javax.swing.JPanel();
        SideMenuBar = new javax.swing.JPanel();
        doctor = new javax.swing.JLabel();
        DOI = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LogOut1 = new javax.swing.JLabel();
        LOI1 = new javax.swing.JLabel();
        pharm = new javax.swing.JLabel();
        PHI = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelRound12 = new Design.PanelRound();
        panelRound13 = new Design.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        c_table = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        LOI2 = new javax.swing.JLabel();
        panelRound15 = new Design.PanelRound();
        panelRound26 = new Design.PanelRound();
        jLabel26 = new javax.swing.JLabel();
        channel = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        panelRound5.setBackground(new java.awt.Color(39, 212, 59));
        panelRound5.setRoundBottomLeft(15);
        panelRound5.setRoundBottomRight(15);
        panelRound5.setRoundTopLeft(15);
        panelRound5.setRoundTopRight(15);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(880, 495));
        setUndecorated(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(239, 252, 245));
        Background.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 232, 221), 4, true));
        Background.setMaximumSize(new java.awt.Dimension(880, 495));
        Background.setMinimumSize(new java.awt.Dimension(880, 495));
        Background.setPreferredSize(new java.awt.Dimension(880, 495));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(70);
        panelRound2.setRoundTopLeft(70);

        panelRound1.setBackground(new java.awt.Color(204, 255, 204));
        panelRound1.setRoundBottomLeft(60);
        panelRound1.setRoundTopLeft(60);
        panelRound1.setLayout(null);

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(60);
        panelRound3.setRoundBottomRight(60);
        panelRound3.setRoundTopLeft(60);
        panelRound3.setRoundTopRight(60);

        Profile_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Profile_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/1Admin.png"))); // NOI18N
        Profile_Image.setToolTipText("");

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addComponent(Profile_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Profile_Image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelRound1.add(panelRound3);
        panelRound3.setBounds(0, 0, 60, 60);

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(72, 100, 114));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Username");
        panelRound1.add(jLabel15);
        jLabel15.setBounds(70, 0, 90, 30);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(72, 100, 114));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Receptionist");
        panelRound1.add(jLabel10);
        jLabel10.setBounds(60, 30, 110, 30);

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        TopBar_Back.setBackground(new java.awt.Color(232, 244, 233));
        TopBar_Back.setPreferredSize(new java.awt.Dimension(656, 50));

        TopBar.setBackground(new java.awt.Color(255, 255, 255));
        TopBar.setPreferredSize(new java.awt.Dimension(656, 50));

        Maxi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Maxi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/max.png"))); // NOI18N
        Maxi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Maxi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaxiMouseClicked(evt);
            }
        });

        Mini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/minimize.png"))); // NOI18N
        Mini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniMouseClicked(evt);
            }
        });

        Cross.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cross.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/Cross.png"))); // NOI18N
        Cross.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cross.setPreferredSize(new java.awt.Dimension(25, 25));
        Cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrossMouseClicked(evt);
            }
        });

        DASHI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_fries_menu_30px_1.png"))); // NOI18N

        Dashboard.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(96, 125, 139));
        Dashboard.setText("Channel Details");

        javax.swing.GroupLayout TopBarLayout = new javax.swing.GroupLayout(TopBar);
        TopBar.setLayout(TopBarLayout);
        TopBarLayout.setHorizontalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DASHI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Mini, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Maxi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Cross, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TopBarLayout.setVerticalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopBarLayout.createSequentialGroup()
                        .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DASHI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Mini, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Maxi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Cross, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout TopBar_BackLayout = new javax.swing.GroupLayout(TopBar_Back);
        TopBar_Back.setLayout(TopBar_BackLayout);
        TopBar_BackLayout.setHorizontalGroup(
            TopBar_BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );
        TopBar_BackLayout.setVerticalGroup(
            TopBar_BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBar_BackLayout.createSequentialGroup()
                .addComponent(TopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        SideMenuBar_Back.setBackground(new java.awt.Color(232, 244, 233));
        SideMenuBar_Back.setMaximumSize(new java.awt.Dimension(228, 495));
        SideMenuBar_Back.setMinimumSize(new java.awt.Dimension(228, 495));
        SideMenuBar_Back.setPreferredSize(new java.awt.Dimension(228, 495));

        SideMenuBar.setBackground(new java.awt.Color(255, 255, 255));
        SideMenuBar.setMaximumSize(new java.awt.Dimension(223, 495));
        SideMenuBar.setMinimumSize(new java.awt.Dimension(223, 495));
        SideMenuBar.setPreferredSize(new java.awt.Dimension(223, 495));

        doctor.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        doctor.setForeground(new java.awt.Color(72, 100, 114));
        doctor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        doctor.setText("Create Channel ");
        doctor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorMouseClicked(evt);
            }
        });

        DOI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_veterinarian_male_25px.png"))); // NOI18N
        DOI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DOI.setPreferredSize(new java.awt.Dimension(34, 34));
        DOI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DOIMouseClicked(evt);
            }
        });

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/dr_pet.png"))); // NOI18N
        Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(72, 100, 114));
        jLabel1.setText("Main Menu");

        LogOut1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        LogOut1.setForeground(new java.awt.Color(72, 100, 114));
        LogOut1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LogOut1.setText("Back");
        LogOut1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut1.setPreferredSize(new java.awt.Dimension(87, 19));
        LogOut1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOut1MouseClicked(evt);
            }
        });

        LOI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_back_arrow_25px.png"))); // NOI18N
        LOI1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOI1.setPreferredSize(new java.awt.Dimension(34, 34));
        LOI1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOI1MouseClicked(evt);
            }
        });

        pharm.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        pharm.setForeground(new java.awt.Color(72, 100, 114));
        pharm.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pharm.setText("Delete Channel");
        pharm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pharm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pharmMouseClicked(evt);
            }
        });

        PHI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_add_trash_25px.png"))); // NOI18N
        PHI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PHI.setPreferredSize(new java.awt.Dimension(34, 34));
        PHI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PHIMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/bb.png"))); // NOI18N

        javax.swing.GroupLayout SideMenuBarLayout = new javax.swing.GroupLayout(SideMenuBar);
        SideMenuBar.setLayout(SideMenuBarLayout);
        SideMenuBarLayout.setHorizontalGroup(
            SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideMenuBarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideMenuBarLayout.createSequentialGroup()
                        .addGroup(SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SideMenuBarLayout.createSequentialGroup()
                                .addComponent(LOI1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LogOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Logo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SideMenuBarLayout.createSequentialGroup()
                        .addGroup(SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DOI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PHI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pharm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctor))
                        .addGap(66, 66, 66))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideMenuBarLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        SideMenuBarLayout.setVerticalGroup(
            SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideMenuBarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PHI, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pharm, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(SideMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LOI1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        javax.swing.GroupLayout SideMenuBar_BackLayout = new javax.swing.GroupLayout(SideMenuBar_Back);
        SideMenuBar_Back.setLayout(SideMenuBar_BackLayout);
        SideMenuBar_BackLayout.setHorizontalGroup(
            SideMenuBar_BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideMenuBar_BackLayout.createSequentialGroup()
                .addComponent(SideMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );
        SideMenuBar_BackLayout.setVerticalGroup(
            SideMenuBar_BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideMenuBar_BackLayout.createSequentialGroup()
                .addComponent(SideMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        panelRound12.setBackground(new java.awt.Color(222, 237, 223));
        panelRound12.setMaximumSize(new java.awt.Dimension(275, 85));
        panelRound12.setMinimumSize(new java.awt.Dimension(275, 85));
        panelRound12.setPreferredSize(new java.awt.Dimension(275, 85));
        panelRound12.setRoundBottomLeft(25);
        panelRound12.setRoundBottomRight(25);
        panelRound12.setRoundTopLeft(25);
        panelRound12.setRoundTopRight(25);

        panelRound13.setBackground(new java.awt.Color(255, 255, 255));
        panelRound13.setMaximumSize(new java.awt.Dimension(270, 165));
        panelRound13.setMinimumSize(new java.awt.Dimension(270, 165));
        panelRound13.setPreferredSize(new java.awt.Dimension(270, 165));
        panelRound13.setRoundBottomLeft(25);
        panelRound13.setRoundBottomRight(25);
        panelRound13.setRoundTopLeft(25);
        panelRound13.setRoundTopRight(25);

        c_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Channel No", "Doctor Name", "Pet Name", "Room No", "Date", "Channel Fee"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        c_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(c_table);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Refresh");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        LOI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_refresh_25px.png"))); // NOI18N
        LOI2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOI2.setPreferredSize(new java.awt.Dimension(34, 34));
        LOI2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOI2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound13Layout = new javax.swing.GroupLayout(panelRound13);
        panelRound13.setLayout(panelRound13Layout);
        panelRound13Layout.setHorizontalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LOI2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(41, 41, 41))
        );
        panelRound13Layout.setVerticalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound13Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LOI2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout panelRound12Layout = new javax.swing.GroupLayout(panelRound12);
        panelRound12.setLayout(panelRound12Layout);
        panelRound12Layout.setHorizontalGroup(
            panelRound12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound12Layout.createSequentialGroup()
                .addComponent(panelRound13, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        panelRound12Layout.setVerticalGroup(
            panelRound12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound12Layout.createSequentialGroup()
                .addComponent(panelRound13, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        panelRound15.setBackground(new java.awt.Color(222, 237, 223));
        panelRound15.setMaximumSize(new java.awt.Dimension(175, 85));
        panelRound15.setMinimumSize(new java.awt.Dimension(175, 85));
        panelRound15.setRoundBottomLeft(25);
        panelRound15.setRoundBottomRight(25);
        panelRound15.setRoundTopLeft(25);
        panelRound15.setRoundTopRight(25);

        panelRound26.setBackground(new java.awt.Color(181, 123, 240));
        panelRound26.setMaximumSize(new java.awt.Dimension(170, 80));
        panelRound26.setMinimumSize(new java.awt.Dimension(170, 80));
        panelRound26.setRoundBottomLeft(25);
        panelRound26.setRoundBottomRight(25);
        panelRound26.setRoundTopLeft(25);
        panelRound26.setRoundTopRight(25);

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Total Appointments ");
        jLabel26.setMaximumSize(new java.awt.Dimension(79, 25));
        jLabel26.setMinimumSize(new java.awt.Dimension(79, 25));
        jLabel26.setPreferredSize(new java.awt.Dimension(79, 25));

        channel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        channel.setForeground(new java.awt.Color(255, 255, 255));
        channel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        channel.setText("00");
        channel.setMaximumSize(new java.awt.Dimension(20, 20));
        channel.setMinimumSize(new java.awt.Dimension(20, 20));
        channel.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_appointment_scheduling_40px_1.png"))); // NOI18N

        javax.swing.GroupLayout panelRound26Layout = new javax.swing.GroupLayout(panelRound26);
        panelRound26.setLayout(panelRound26Layout);
        panelRound26Layout.setHorizontalGroup(
            panelRound26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound26Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelRound26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(channel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addGap(15, 15, 15))
        );
        panelRound26Layout.setVerticalGroup(
            panelRound26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRound26Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(channel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout panelRound15Layout = new javax.swing.GroupLayout(panelRound15);
        panelRound15.setLayout(panelRound15Layout);
        panelRound15Layout.setHorizontalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound15Layout.createSequentialGroup()
                .addComponent(panelRound26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        panelRound15Layout.setVerticalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound15Layout.createSequentialGroup()
                .addComponent(panelRound26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(SideMenuBar_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TopBar_Back, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(panelRound12, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(panelRound15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(3, 3, 3))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(TopBar_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(panelRound12, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
            .addComponent(SideMenuBar_Back, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1200, 675));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        ResultSet r = new Channel_Search().searchChannel();
        DefaultTableModel dtm = (DefaultTableModel) c_table.getModel();
        dtm.setRowCount(0); //sets the number of rows in the model
        try{
            Vector v;
            while (r.next()){
                v = new Vector();
                v.add(r.getString("channel_no"));
                v.add(r.getString("dr_name"));
                v.add(r.getString("pet_name"));
                v.add(r.getString("room_no"));
                v.add(r.getString("date"));
                v.add(r.getString("channel_fee"));

                dtm.addRow(v);

                //Adds a row to the end of the model
            }
            DBConnection.closeCon();
        }
        catch (Exception e) {
            e.printStackTrace();
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void c_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_tableMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_c_tableMouseClicked

    private void pharmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pharmMouseClicked
        new Delete_Channel_pop1().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_pharmMouseClicked

    private void LOI1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOI1MouseClicked
          new Receptionist_Dashboard(uname).setVisible(true);
        super.dispose();
    }//GEN-LAST:event_LOI1MouseClicked

    private void LogOut1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut1MouseClicked
     new Receptionist_Dashboard(uname).setVisible(true);
        super.dispose();
    }//GEN-LAST:event_LogOut1MouseClicked

    private void doctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorMouseClicked
        new Create_Channel().setVisible(true);
        //super.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorMouseClicked

    private void CrossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrossMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CrossMouseClicked

    private void MiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniMouseClicked
        // Minimize:
        this.setExtendedState(Channel.ICONIFIED);
    }//GEN-LAST:event_MiniMouseClicked

    private void MaxiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaxiMouseClicked
        // Maximize:
        if(this.getExtendedState()!=Channel.MAXIMIZED_BOTH){
            this.setExtendedState(Channel.MAXIMIZED_BOTH);
        }
        else{
            this.setExtendedState(Channel.NORMAL);
        }
    }//GEN-LAST:event_MaxiMouseClicked

    private void LOI2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOI2MouseClicked
       ResultSet r = new Channel_Search().searchChannel();
        DefaultTableModel dtm = (DefaultTableModel) c_table.getModel();
        dtm.setRowCount(0); //sets the number of rows in the model
        try{
            Vector v;
            while (r.next()){
                v = new Vector();
                v.add(r.getString("channel_no"));
                v.add(r.getString("dr_name"));
                v.add(r.getString("pet_name"));
                v.add(r.getString("room_no"));
                v.add(r.getString("date"));
                v.add(r.getString("channel_fee"));

                dtm.addRow(v);

                //Adds a row to the end of the model
            }
            DBConnection.closeCon();
        }
        catch (Exception e) {
            e.printStackTrace();
        }    
    }//GEN-LAST:event_LOI2MouseClicked

    private void DOIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOIMouseClicked
        // TODO add your handling code here:
        new Create_Channel().setVisible(true);
    }//GEN-LAST:event_DOIMouseClicked

    private void PHIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PHIMouseClicked
        // TODO add your handling code here:
        new Delete_Channel_pop1().setVisible(true);
    }//GEN-LAST:event_PHIMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Channel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Channel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Channel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Channel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            String user_name;
            public void run() {
                new Channel(user_name).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Cross;
    private javax.swing.JLabel DASHI;
    private javax.swing.JLabel DOI;
    private javax.swing.JLabel Dashboard;
    private javax.swing.JLabel LOI1;
    private javax.swing.JLabel LOI2;
    private javax.swing.JLabel LogOut1;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Maxi;
    private javax.swing.JLabel Mini;
    private javax.swing.JLabel PHI;
    private javax.swing.JLabel Profile_Image;
    private javax.swing.JPanel SideMenuBar;
    private javax.swing.JPanel SideMenuBar_Back;
    private javax.swing.JPanel TopBar;
    private javax.swing.JPanel TopBar_Back;
    private javax.swing.JTable c_table;
    private javax.swing.JLabel channel;
    private javax.swing.JLabel doctor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private Design.PanelRound panelRound1;
    private Design.PanelRound panelRound12;
    private Design.PanelRound panelRound13;
    private Design.PanelRound panelRound15;
    private Design.PanelRound panelRound2;
    private Design.PanelRound panelRound26;
    private Design.PanelRound panelRound3;
    private Design.PanelRound panelRound5;
    private javax.swing.JLabel pharm;
    // End of variables declaration//GEN-END:variables
}
