/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Doctor;


import View.Receptionist.*;
import Model.DBConnection;
import Model.Doctor_Searchtable;
import Model.Pet_Searchtable;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Deshan Asanka
 */
public class Doc_pet_Details extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Dashboard
     */
    String uname;
    public Doc_pet_Details(String user_name) {
        initComponents();
  this.uname = user_name;
        jLabel15.setText(uname);
        
        ResultSet r = new Pet_Searchtable().searchpet();
        DefaultTableModel dtm = (DefaultTableModel) pet_table.getModel();
        dtm.setRowCount(0); //sets the number of rows in the model
        try{
            Vector v;
            while (r.next()){
                v = new Vector();
                v.add(r.getString("id"));
                v.add(r.getString("name"));
                v.add(r.getString("category"));
                v.add(r.getString("gender"));
                v.add(r.getString("age"));
                v.add(r.getString("owner_name"));
                v.add(r.getString("owner_contactno"));

                dtm.addRow(v);

                //Adds a row to the end of the model
            }
            DBConnection.closeCon();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        
        int p_count = pet_table.getRowCount(); 
  pet.setText(String.valueOf(p_count));
        
    }
    

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound5 = new Design.PanelRound();
        Background = new javax.swing.JPanel();
        panelRound2 = new Design.PanelRound();
        panelRound16 = new Design.PanelRound();
        panelRound15 = new Design.PanelRound();
        Profile_Image = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TopBar_Back = new javax.swing.JPanel();
        TopBar = new javax.swing.JPanel();
        Maxi = new javax.swing.JLabel();
        Mini = new javax.swing.JLabel();
        Cross = new javax.swing.JLabel();
        DASHI = new javax.swing.JLabel();
        Dashboard = new javax.swing.JLabel();
        LogOut1 = new javax.swing.JLabel();
        LOI1 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        panelRound12 = new Design.PanelRound();
        panelRound13 = new Design.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        pet_table = new javax.swing.JTable();
        panelRound17 = new Design.PanelRound();
        panelRound26 = new Design.PanelRound();
        jLabel26 = new javax.swing.JLabel();
        pet = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        panelRound5.setBackground(new java.awt.Color(39, 212, 59));
        panelRound5.setRoundBottomLeft(15);
        panelRound5.setRoundBottomRight(15);
        panelRound5.setRoundTopLeft(15);
        panelRound5.setRoundTopRight(15);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(880, 495));
        setUndecorated(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(239, 252, 245));
        Background.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(220, 232, 221), 4, true));
        Background.setMaximumSize(new java.awt.Dimension(880, 495));
        Background.setMinimumSize(new java.awt.Dimension(880, 495));
        Background.setPreferredSize(new java.awt.Dimension(880, 495));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(70);
        panelRound2.setRoundTopLeft(70);

        panelRound16.setBackground(new java.awt.Color(204, 255, 204));
        panelRound16.setRoundBottomLeft(60);
        panelRound16.setRoundTopLeft(60);
        panelRound16.setLayout(null);

        panelRound15.setBackground(new java.awt.Color(255, 255, 255));
        panelRound15.setRoundBottomLeft(60);
        panelRound15.setRoundBottomRight(60);
        panelRound15.setRoundTopLeft(60);
        panelRound15.setRoundTopRight(60);

        Profile_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Profile_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/1Doctor.png"))); // NOI18N

        javax.swing.GroupLayout panelRound15Layout = new javax.swing.GroupLayout(panelRound15);
        panelRound15.setLayout(panelRound15Layout);
        panelRound15Layout.setHorizontalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Profile_Image))
        );
        panelRound15Layout.setVerticalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Profile_Image))
        );

        panelRound16.add(panelRound15);
        panelRound15.setBounds(0, 0, 60, 60);

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(72, 100, 114));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Username");
        panelRound16.add(jLabel15);
        jLabel15.setBounds(70, 0, 90, 30);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(72, 100, 114));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Doctor");
        panelRound16.add(jLabel10);
        jLabel10.setBounds(70, 30, 90, 30);

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(panelRound16, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(panelRound16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        TopBar_Back.setBackground(new java.awt.Color(232, 244, 233));
        TopBar_Back.setPreferredSize(new java.awt.Dimension(656, 50));

        TopBar.setBackground(new java.awt.Color(255, 255, 255));
        TopBar.setPreferredSize(new java.awt.Dimension(656, 50));

        Maxi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Maxi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/max.png"))); // NOI18N
        Maxi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Maxi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaxiMouseClicked(evt);
            }
        });

        Mini.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/minimize.png"))); // NOI18N
        Mini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniMouseClicked(evt);
            }
        });

        Cross.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cross.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/Cross.png"))); // NOI18N
        Cross.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cross.setPreferredSize(new java.awt.Dimension(25, 25));
        Cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrossMouseClicked(evt);
            }
        });

        DASHI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_fries_menu_30px_1.png"))); // NOI18N

        Dashboard.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(96, 125, 139));
        Dashboard.setText("Pet Details");

        javax.swing.GroupLayout TopBarLayout = new javax.swing.GroupLayout(TopBar);
        TopBar.setLayout(TopBarLayout);
        TopBarLayout.setHorizontalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DASHI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Mini, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Maxi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Cross, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TopBarLayout.setVerticalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopBarLayout.createSequentialGroup()
                        .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DASHI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Mini, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Maxi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Cross, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout TopBar_BackLayout = new javax.swing.GroupLayout(TopBar_Back);
        TopBar_Back.setLayout(TopBar_BackLayout);
        TopBar_BackLayout.setHorizontalGroup(
            TopBar_BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1192, Short.MAX_VALUE)
        );
        TopBar_BackLayout.setVerticalGroup(
            TopBar_BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBar_BackLayout.createSequentialGroup()
                .addComponent(TopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        LogOut1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        LogOut1.setForeground(new java.awt.Color(72, 100, 114));
        LogOut1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LogOut1.setText("Back");
        LogOut1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut1.setPreferredSize(new java.awt.Dimension(87, 19));
        LogOut1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOut1MouseClicked(evt);
            }
        });

        LOI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_back_arrow_25px.png"))); // NOI18N
        LOI1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOI1.setPreferredSize(new java.awt.Dimension(34, 34));
        LOI1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LOI1MouseClicked(evt);
            }
        });

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/dr_pet.png"))); // NOI18N
        Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        panelRound12.setBackground(new java.awt.Color(222, 237, 223));
        panelRound12.setMaximumSize(new java.awt.Dimension(275, 85));
        panelRound12.setMinimumSize(new java.awt.Dimension(275, 85));
        panelRound12.setRoundBottomLeft(25);
        panelRound12.setRoundBottomRight(25);
        panelRound12.setRoundTopLeft(25);
        panelRound12.setRoundTopRight(25);

        panelRound13.setBackground(new java.awt.Color(255, 255, 255));
        panelRound13.setMaximumSize(new java.awt.Dimension(270, 165));
        panelRound13.setMinimumSize(new java.awt.Dimension(270, 165));
        panelRound13.setRoundBottomLeft(25);
        panelRound13.setRoundBottomRight(25);
        panelRound13.setRoundTopLeft(25);
        panelRound13.setRoundTopRight(25);

        pet_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Pet ID", "Name", "Category ", "Gender", "Age in months", "Owner name", "Contact No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        pet_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pet_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pet_table);

        javax.swing.GroupLayout panelRound13Layout = new javax.swing.GroupLayout(panelRound13);
        panelRound13.setLayout(panelRound13Layout);
        panelRound13Layout.setHorizontalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelRound13Layout.setVerticalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound13Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRound12Layout = new javax.swing.GroupLayout(panelRound12);
        panelRound12.setLayout(panelRound12Layout);
        panelRound12Layout.setHorizontalGroup(
            panelRound12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound12Layout.createSequentialGroup()
                .addComponent(panelRound13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound12Layout.setVerticalGroup(
            panelRound12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound12Layout.createSequentialGroup()
                .addComponent(panelRound13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        panelRound17.setBackground(new java.awt.Color(222, 237, 223));
        panelRound17.setMaximumSize(new java.awt.Dimension(175, 85));
        panelRound17.setMinimumSize(new java.awt.Dimension(175, 85));
        panelRound17.setRoundBottomLeft(25);
        panelRound17.setRoundBottomRight(25);
        panelRound17.setRoundTopLeft(25);
        panelRound17.setRoundTopRight(25);

        panelRound26.setBackground(new java.awt.Color(181, 123, 240));
        panelRound26.setMaximumSize(new java.awt.Dimension(170, 80));
        panelRound26.setMinimumSize(new java.awt.Dimension(170, 80));
        panelRound26.setRoundBottomLeft(25);
        panelRound26.setRoundBottomRight(25);
        panelRound26.setRoundTopLeft(25);
        panelRound26.setRoundTopRight(25);

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Total Pets ");
        jLabel26.setMaximumSize(new java.awt.Dimension(79, 25));
        jLabel26.setMinimumSize(new java.awt.Dimension(79, 25));
        jLabel26.setPreferredSize(new java.awt.Dimension(79, 25));

        pet.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        pet.setForeground(new java.awt.Color(255, 255, 255));
        pet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pet.setText("00");
        pet.setMaximumSize(new java.awt.Dimension(20, 20));
        pet.setMinimumSize(new java.awt.Dimension(20, 20));
        pet.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_puppy_40px_1.png"))); // NOI18N

        javax.swing.GroupLayout panelRound26Layout = new javax.swing.GroupLayout(panelRound26);
        panelRound26.setLayout(panelRound26Layout);
        panelRound26Layout.setHorizontalGroup(
            panelRound26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound26Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelRound26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(pet, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        panelRound26Layout.setVerticalGroup(
            panelRound26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound26Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound26Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout panelRound17Layout = new javax.swing.GroupLayout(panelRound17);
        panelRound17.setLayout(panelRound17Layout);
        panelRound17Layout.setHorizontalGroup(
            panelRound17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound17Layout.createSequentialGroup()
                .addComponent(panelRound26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        panelRound17Layout.setVerticalGroup(
            panelRound17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound17Layout.createSequentialGroup()
                .addComponent(panelRound26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopBar_Back, javax.swing.GroupLayout.DEFAULT_SIZE, 1192, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(panelRound12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(panelRound17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 475, Short.MAX_VALUE)
                        .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(LOI1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LogOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(TopBar_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelRound17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LOI1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1200, 675));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LOI1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LOI1MouseClicked
      new doctordashboard(uname).setVisible(true);   
        super.dispose();
    }//GEN-LAST:event_LOI1MouseClicked

    private void LogOut1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOut1MouseClicked
new doctordashboard(uname).setVisible(true);   
        super.dispose();
    }//GEN-LAST:event_LogOut1MouseClicked

    private void CrossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrossMouseClicked
      new doctordashboard(uname).setVisible(true);   
        super.dispose();
    }//GEN-LAST:event_CrossMouseClicked

    private void MiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniMouseClicked
        // Minimize:
        this.setExtendedState(Doc_pet_Details.ICONIFIED);
    }//GEN-LAST:event_MiniMouseClicked

    private void MaxiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaxiMouseClicked
        // Maximize:
        if(this.getExtendedState()!=Doc_pet_Details.MAXIMIZED_BOTH){
            this.setExtendedState(Doc_pet_Details.MAXIMIZED_BOTH);
        }
        else{
            this.setExtendedState(Doc_pet_Details.NORMAL);
        }
    }//GEN-LAST:event_MaxiMouseClicked

    private void pet_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pet_tableMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_pet_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doc_pet_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doc_pet_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doc_pet_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doc_pet_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            String user_name;
            public void run() {
                new Doc_pet_Details(user_name).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Cross;
    private javax.swing.JLabel DASHI;
    private javax.swing.JLabel Dashboard;
    private javax.swing.JLabel LOI1;
    private javax.swing.JLabel LogOut1;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Maxi;
    private javax.swing.JLabel Mini;
    private javax.swing.JLabel Profile_Image;
    private javax.swing.JPanel TopBar;
    private javax.swing.JPanel TopBar_Back;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JScrollPane jScrollPane1;
    private Design.PanelRound panelRound12;
    private Design.PanelRound panelRound13;
    private Design.PanelRound panelRound15;
    private Design.PanelRound panelRound16;
    private Design.PanelRound panelRound17;
    private Design.PanelRound panelRound2;
    private Design.PanelRound panelRound26;
    private Design.PanelRound panelRound5;
    private javax.swing.JLabel pet;
    private javax.swing.JTable pet_table;
    // End of variables declaration//GEN-END:variables
}
