/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Doctor;


import Control.prescription_register_controller;
import Model.DBConnection;
import Model.Dr_Channel_channelno;
import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Deshan Asanka
 */
public class prescrip_create extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Dashboard
     */
 
    public prescrip_create(String channel_no) {
        initComponents();
        
        setBackground(new Color(1.0f,1.0f,1.0f,0.8f));   
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 35, 35));

        String no= channel_no ;
        
        ResultSet r = new Dr_Channel_channelno().searchchannel(no);
        DefaultTableModel dtm = (DefaultTableModel) channe_table.getModel();
        dtm.setRowCount(0); //sets the number of rows in the model
        try{
            Vector v;
            while (r.next()){
                v = new Vector();
                v.add(r.getString("channel_no"));
                v.add(r.getString("pet_name"));
                v.add(r.getString("room_no"));
                v.add(r.getString("date"));

                dtm.addRow(v);

                //Adds a row to the end of the model
            }
            DBConnection.closeCon();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
               
    }
    

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void print(){
        String id = pres_id.getText();
        String no = Channel_no.getText();
        String petname = Pet_name.getText();
        String date = Date.getText();
        String desease = desease_type.getText();
        String description = Description.getText();
        
      
        txtprint.setText(txtprint.getText()+"\t\tDr.Pet" +"\n");
        txtprint.setText(txtprint.getText()+"\t              Medical Prescription" +"\n");
        txtprint.setText(txtprint.getText()+"--------------------------------------------------------------------------------------\n");
        txtprint.setText(txtprint.getText()+"Prescription ID: " + id + "\n");
        txtprint.setText(txtprint.getText()+"Channel No: " + no + "\n");
        txtprint.setText(txtprint.getText()+"Pet name: " + petname + "\n");
        txtprint.setText(txtprint.getText()+"Date: " + date+ "\n");
        txtprint.setText(txtprint.getText()+"Desease type: " + desease+ "\n");
        txtprint.setText(txtprint.getText()+"Description: " + description+ "\n");
        txtprint.setText(txtprint.getText()+"--------------------------------------------------------------------------------------\n");
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound5 = new Design.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelRound4 = new Design.PanelRound();
        panelRound7 = new Design.PanelRound();
        username = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        id = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        contactno = new javax.swing.JTextField();
        NIC = new javax.swing.JTextField();
        roomno = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        specialization = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        panelRound14 = new Design.PanelRound();
        panelRound15 = new Design.PanelRound();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        edit = new Design.PanelRound();
        edit1 = new javax.swing.JLabel();
        back = new Design.PanelRound();
        backtxt = new javax.swing.JLabel();
        back1 = new Design.PanelRound();
        backtxt1 = new javax.swing.JLabel();
        Channel_no = new javax.swing.JTextField();
        pres_id = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        Pet_name = new javax.swing.JTextField();
        panelRound12 = new Design.PanelRound();
        panelRound13 = new Design.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        channe_table = new javax.swing.JTable();
        panelRound16 = new Design.PanelRound();
        panelRound17 = new Design.PanelRound();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtprint = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextArea();
        edit4 = new Design.PanelRound();
        create = new javax.swing.JLabel();
        edit6 = new Design.PanelRound();
        print = new javax.swing.JLabel();
        Date = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        desease_type = new javax.swing.JTextField();
        Dashboard = new javax.swing.JLabel();
        DASHI = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        panelRound5.setBackground(new java.awt.Color(39, 212, 59));
        panelRound5.setRoundBottomLeft(15);
        panelRound5.setRoundBottomRight(15);
        panelRound5.setRoundTopLeft(15);
        panelRound5.setRoundTopRight(15);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel7.setText("Doctor ID :");

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel16.setText("Gender :");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADD");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CANCEL");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        panelRound4.setBackground(new java.awt.Color(193, 193, 193));
        panelRound4.setRoundBottomLeft(15);
        panelRound4.setRoundBottomRight(15);
        panelRound4.setRoundTopLeft(15);
        panelRound4.setRoundTopRight(15);

        panelRound7.setBackground(new java.awt.Color(39, 212, 59));
        panelRound7.setRoundBottomLeft(15);
        panelRound7.setRoundBottomRight(15);
        panelRound7.setRoundTopLeft(15);
        panelRound7.setRoundTopRight(15);

        username.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel17.setText("Password :");

        password.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        id.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        year.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        year.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        name.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        contactno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        contactno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        contactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnoActionPerformed(evt);
            }
        });

        NIC.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        NIC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        roomno.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        roomno.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        male.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        male.setText("Male");
        male.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        female.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        female.setText("Female");
        female.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        specialization.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        specialization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anesthesia", "Animal Welfare", "Behavior", "Dentistry", "Dermatology", "Oncology", "Microbiology", "Nutrition", "Ophthalmology", "Pathology", "Radiology", "Surgery", "Theriogenology" }));
        specialization.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel14.setText("Username :");

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel12.setText("Contact No:");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel13.setText("Room No :");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel11.setText("Years of Experience :");

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel18.setText("Specialization :");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel9.setText("NIC N0 :");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel8.setText("Doctor Name :");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/ADD POP.png"))); // NOI18N
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelRound14.setBackground(new java.awt.Color(222, 237, 223));
        panelRound14.setMaximumSize(new java.awt.Dimension(275, 85));
        panelRound14.setMinimumSize(new java.awt.Dimension(275, 85));
        panelRound14.setRoundBottomLeft(25);
        panelRound14.setRoundBottomRight(25);
        panelRound14.setRoundTopLeft(25);
        panelRound14.setRoundTopRight(25);

        panelRound15.setBackground(new java.awt.Color(255, 255, 255));
        panelRound15.setMaximumSize(new java.awt.Dimension(270, 165));
        panelRound15.setMinimumSize(new java.awt.Dimension(270, 165));
        panelRound15.setRoundBottomLeft(25);
        panelRound15.setRoundBottomRight(25);
        panelRound15.setRoundTopLeft(25);
        panelRound15.setRoundTopRight(25);

        jTextField1.setBackground(new java.awt.Color(204, 255, 204));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound15Layout = new javax.swing.GroupLayout(panelRound15);
        panelRound15.setLayout(panelRound15Layout);
        panelRound15Layout.setHorizontalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound15Layout.setVerticalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelRound14Layout = new javax.swing.GroupLayout(panelRound14);
        panelRound14.setLayout(panelRound14Layout);
        panelRound14Layout.setHorizontalGroup(
            panelRound14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound14Layout.createSequentialGroup()
                .addComponent(panelRound15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound14Layout.setVerticalGroup(
            panelRound14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound14Layout.createSequentialGroup()
                .addComponent(panelRound15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1215, 630));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 2, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Enter the Description along with the dose");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(710, 190, 420, 20);

        edit.setBackground(new java.awt.Color(39, 212, 59));
        edit.setRoundBottomLeft(15);
        edit.setRoundBottomRight(15);
        edit.setRoundTopLeft(15);
        edit.setRoundTopRight(15);
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });

        edit1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        edit1.setForeground(new java.awt.Color(255, 255, 255));
        edit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit1.setText("Edit");
        edit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit1MouseClicked(evt);
            }
        });
        edit.add(edit1);

        getContentPane().add(edit);
        edit.setBounds(553, 835, 115, 33);

        back.setBackground(new java.awt.Color(204, 204, 204));
        back.setRoundBottomLeft(15);
        back.setRoundBottomRight(15);
        back.setRoundTopLeft(15);
        back.setRoundTopRight(15);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        backtxt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        backtxt.setForeground(new java.awt.Color(255, 255, 255));
        backtxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backtxt.setText("Back");
        backtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backtxtMouseClicked(evt);
            }
        });
        back.add(backtxt);

        getContentPane().add(back);
        back.setBounds(85, 835, 115, 33);

        back1.setBackground(new java.awt.Color(153, 153, 153));
        back1.setRoundBottomLeft(15);
        back1.setRoundBottomRight(15);
        back1.setRoundTopLeft(15);
        back1.setRoundTopRight(15);
        back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back1MouseClicked(evt);
            }
        });

        backtxt1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        backtxt1.setForeground(new java.awt.Color(255, 255, 255));
        backtxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backtxt1.setText("Back");
        backtxt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backtxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backtxt1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout back1Layout = new javax.swing.GroupLayout(back1);
        back1.setLayout(back1Layout);
        back1Layout.setHorizontalGroup(
            back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backtxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );
        back1Layout.setVerticalGroup(
            back1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backtxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        getContentPane().add(back1);
        back1.setBounds(660, 550, 115, 33);

        Channel_no.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Channel_no.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Channel_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Channel_noActionPerformed(evt);
            }
        });
        getContentPane().add(Channel_no);
        Channel_no.setBounds(220, 200, 230, 30);

        pres_id.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        pres_id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pres_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pres_idActionPerformed(evt);
            }
        });
        getContentPane().add(pres_id);
        pres_id.setBounds(220, 140, 230, 30);

        jLabel25.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel25.setText("Prescription ID :");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(50, 140, 170, 30);

        jLabel26.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel26.setText("Channel No :");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(50, 200, 140, 30);

        jLabel36.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel36.setText("Pet Name :");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(50, 250, 120, 30);

        Pet_name.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Pet_name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(Pet_name);
        Pet_name.setBounds(220, 250, 230, 30);

        panelRound12.setBackground(new java.awt.Color(222, 237, 223));
        panelRound12.setMaximumSize(new java.awt.Dimension(275, 85));
        panelRound12.setMinimumSize(new java.awt.Dimension(275, 85));
        panelRound12.setRoundBottomLeft(25);
        panelRound12.setRoundBottomRight(25);
        panelRound12.setRoundTopLeft(25);
        panelRound12.setRoundTopRight(25);

        panelRound13.setBackground(new java.awt.Color(255, 255, 255));
        panelRound13.setMaximumSize(new java.awt.Dimension(270, 165));
        panelRound13.setMinimumSize(new java.awt.Dimension(270, 165));
        panelRound13.setRoundBottomLeft(25);
        panelRound13.setRoundBottomRight(25);
        panelRound13.setRoundTopLeft(25);
        panelRound13.setRoundTopRight(25);

        channe_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Channel No", "Pet Name", "Room No", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        channe_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                channe_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(channe_table);

        javax.swing.GroupLayout panelRound13Layout = new javax.swing.GroupLayout(panelRound13);
        panelRound13.setLayout(panelRound13Layout);
        panelRound13Layout.setHorizontalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound13Layout.setVerticalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelRound12Layout = new javax.swing.GroupLayout(panelRound12);
        panelRound12.setLayout(panelRound12Layout);
        panelRound12Layout.setHorizontalGroup(
            panelRound12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound12Layout.createSequentialGroup()
                .addComponent(panelRound13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound12Layout.setVerticalGroup(
            panelRound12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound12Layout.createSequentialGroup()
                .addComponent(panelRound13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        getContentPane().add(panelRound12);
        panelRound12.setBounds(50, 350, 570, 229);

        panelRound16.setBackground(new java.awt.Color(222, 237, 223));
        panelRound16.setMaximumSize(new java.awt.Dimension(275, 85));
        panelRound16.setMinimumSize(new java.awt.Dimension(275, 85));
        panelRound16.setRoundBottomLeft(25);
        panelRound16.setRoundBottomRight(25);
        panelRound16.setRoundTopLeft(25);
        panelRound16.setRoundTopRight(25);

        panelRound17.setBackground(new java.awt.Color(255, 255, 255));
        panelRound17.setMaximumSize(new java.awt.Dimension(270, 165));
        panelRound17.setMinimumSize(new java.awt.Dimension(270, 165));
        panelRound17.setRoundBottomLeft(25);
        panelRound17.setRoundBottomRight(25);
        panelRound17.setRoundTopLeft(25);
        panelRound17.setRoundTopRight(25);

        txtprint.setColumns(20);
        txtprint.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtprint.setRows(5);
        txtprint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0), 2));
        jScrollPane3.setViewportView(txtprint);

        javax.swing.GroupLayout panelRound17Layout = new javax.swing.GroupLayout(panelRound17);
        panelRound17.setLayout(panelRound17Layout);
        panelRound17Layout.setHorizontalGroup(
            panelRound17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound17Layout.setVerticalGroup(
            panelRound17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelRound16Layout = new javax.swing.GroupLayout(panelRound16);
        panelRound16.setLayout(panelRound16Layout);
        panelRound16Layout.setHorizontalGroup(
            panelRound16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound16Layout.createSequentialGroup()
                .addComponent(panelRound17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        panelRound16Layout.setVerticalGroup(
            panelRound16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound16Layout.createSequentialGroup()
                .addComponent(panelRound17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        getContentPane().add(panelRound16);
        panelRound16.setBounds(640, 320, 530, 210);

        Description.setColumns(20);
        Description.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Description.setRows(5);
        jScrollPane2.setViewportView(Description);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(710, 210, 450, 90);

        edit4.setBackground(new java.awt.Color(15, 225, 111));
        edit4.setRoundBottomLeft(15);
        edit4.setRoundBottomRight(15);
        edit4.setRoundTopLeft(15);
        edit4.setRoundTopRight(15);
        edit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit4MouseClicked(evt);
            }
        });

        create.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        create.setForeground(new java.awt.Color(255, 255, 255));
        create.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create.setText("Create");
        create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout edit4Layout = new javax.swing.GroupLayout(edit4);
        edit4.setLayout(edit4Layout);
        edit4Layout.setHorizontalGroup(
            edit4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(create, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );
        edit4Layout.setVerticalGroup(
            edit4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(create, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        getContentPane().add(edit4);
        edit4.setBounds(1030, 550, 115, 33);

        edit6.setBackground(new java.awt.Color(15, 225, 111));
        edit6.setRoundBottomLeft(15);
        edit6.setRoundBottomRight(15);
        edit6.setRoundTopLeft(15);
        edit6.setRoundTopRight(15);
        edit6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit6MouseClicked(evt);
            }
        });

        print.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        print.setText("Print");
        print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout edit6Layout = new javax.swing.GroupLayout(edit6);
        edit6.setLayout(edit6Layout);
        edit6Layout.setHorizontalGroup(
            edit6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(print, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        edit6Layout.setVerticalGroup(
            edit6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(print, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        getContentPane().add(edit6);
        edit6.setBounds(840, 550, 120, 33);

        Date.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Date.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(Date);
        Date.setBounds(220, 300, 230, 30);

        jLabel37.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel37.setText("Date :");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(50, 300, 120, 30);

        jLabel35.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel35.setText("Description :");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(540, 190, 140, 30);

        jLabel32.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel32.setText("Desease Type : ");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(540, 140, 150, 30);

        desease_type.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        desease_type.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        desease_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desease_typeActionPerformed(evt);
            }
        });
        getContentPane().add(desease_type);
        desease_type.setBounds(710, 140, 330, 30);

        Dashboard.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(96, 125, 139));
        Dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dashboard.setText("Create Prescription");
        getContentPane().add(Dashboard);
        Dashboard.setBounds(150, 80, 240, 31);

        DASHI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/icons8_fries_menu_30px_1.png"))); // NOI18N
        getContentPane().add(DASHI);
        DASHI.setBounds(120, 80, 30, 31);

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Image/edit_B.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1200, 640);

        setSize(new java.awt.Dimension(1200, 675));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
    

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        // new pop_pass().setVisible(true);
      
    }//GEN-LAST:event_jLabel6MouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void contactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnoActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void edit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_edit1MouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
     // TODO add your handling code here:
    }//GEN-LAST:event_editMouseClicked

    private void backtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backtxtMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked

    }//GEN-LAST:event_backMouseClicked

    private void backtxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backtxt1MouseClicked
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_backtxt1MouseClicked

    private void back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back1MouseClicked
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_back1MouseClicked

    private void Channel_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Channel_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Channel_noActionPerformed

    private void pres_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pres_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pres_idActionPerformed

    private void desease_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desease_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desease_typeActionPerformed

    private void channe_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_channe_tableMouseClicked
        DefaultTableModel d1 = (DefaultTableModel)channe_table.getModel() ;
        int SelectIndex = channe_table.getSelectedRow();

        Channel_no.setText(d1.getValueAt(SelectIndex, 0).toString());
        Pet_name.setText(d1.getValueAt(SelectIndex, 1).toString());

        Date.setText(d1.getValueAt(SelectIndex, 3).toString());

    }//GEN-LAST:event_channe_tableMouseClicked

    private void createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseClicked
if (pres_id.getText().trim().isEmpty()|| desease_type.getText().trim().isEmpty()|| Description.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Add all the credentials", "Error" , JOptionPane.ERROR_MESSAGE);}
        else{
            prescription_register_controller.Form(pres_id.getText(),Channel_no.getText(), Pet_name.getText(),Date.getText(),desease_type.getText(),Description.getText());
print();
clearField(); 

        }
    }//GEN-LAST:event_createMouseClicked

    private void edit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit4MouseClicked

    }//GEN-LAST:event_edit4MouseClicked

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        try {
            txtprint.print();
        } catch (PrinterException ex) {
            Logger.getLogger(prescrip_create.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printMouseClicked

    private void edit6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_edit6MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public void clearField(){
pres_id.setText("");
Channel_no.setText("");
Pet_name.setText("");
Date.setText("");
desease_type.setText("");
Description.setText("");
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prescrip_create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prescrip_create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prescrip_create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prescrip_create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
      
        //</editor-fold>
        //</editor-fold>
      
 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            String no;
            public void run() {
                new prescrip_create(no).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Channel_no;
    private javax.swing.JLabel DASHI;
    private javax.swing.JLabel Dashboard;
    private javax.swing.JTextField Date;
    private javax.swing.JTextArea Description;
    private javax.swing.JTextField NIC;
    private javax.swing.JTextField Pet_name;
    private Design.PanelRound back;
    private Design.PanelRound back1;
    private javax.swing.JLabel background;
    private javax.swing.JLabel backtxt;
    private javax.swing.JLabel backtxt1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable channe_table;
    private javax.swing.JTextField contactno;
    private javax.swing.JLabel create;
    private javax.swing.JTextField desease_type;
    private Design.PanelRound edit;
    private javax.swing.JLabel edit1;
    private Design.PanelRound edit4;
    private Design.PanelRound edit6;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private Design.PanelRound panelRound12;
    private Design.PanelRound panelRound13;
    private Design.PanelRound panelRound14;
    private Design.PanelRound panelRound15;
    private Design.PanelRound panelRound16;
    private Design.PanelRound panelRound17;
    private Design.PanelRound panelRound4;
    private Design.PanelRound panelRound5;
    private Design.PanelRound panelRound7;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField pres_id;
    private javax.swing.JLabel print;
    private javax.swing.JTextField roomno;
    private javax.swing.JComboBox<String> specialization;
    private javax.swing.JTextArea txtprint;
    private javax.swing.JTextField username;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
